daikon/src/main/java/org/talend/daikon/exception/ExceptionContext.java
daikon/src/main/java/org/talend/daikon/exception/TalendRuntimeException.java
daikon/src/main/java/org/talend/daikon/exception/error/ErrorCode.java
daikon/src/main/java/org/talend/daikon/i18n/ClassBasedI18nMessages.java
daikon/src/main/java/org/talend/daikon/i18n/ClassLoaderBasedI18nMessages.java
daikon/src/main/java/org/talend/daikon/i18n/I18nMessages.java
daikon/src/main/java/org/talend/daikon/i18n/LocaleProvider.java
daikon/src/main/java/org/talend/daikon/security/CryptoHelper.java
daikon/src/test/java/org/talend/daikon/i18n/I18nMessagesTest.java

Trivial modifications (except perhaps the getFormatedMessage method name change -- I couldn't find anyone who used it outside of daikon).

Fix some comments and spelling errors.

---

pom.xml

Signed-off-by: olivier lamy <olamy@apache.org>

define license in pom to help maven tooling

---

daikon/src/main/java/org/talend/daikon/properties/presentation/Form.java
daikon/src/test/java/org/talend/daikon/properties/test/PropertiesTestUtils.java

I removed the **Form.children** that was not used appart from test and that can be gotten by using **Form.widgets().properties**
this reduce the size of the serialized data 
from
jackson:1 MB
jsonio:34 KB
to
jackson:494 KB
jsonio:32 KB

removed children from Form, widget list is enougth

---

daikon/src/main/java/org/talend/daikon/properties/Properties.java
daikon/src/main/java/org/talend/daikon/properties/PropertiesDynamicMethodHelper.java
daikon/src/test/java/org/talend/daikon/properties/PropertiesTest.java
daikon/src/test/java/org/talend/daikon/properties/test/PropertiesTestUtils.java
daikon/src/test/java/org/talend/daikon/properties/testproperties/nestedprop/NestedNestedProperties.java
daikon/src/test/java/org/talend/daikon/properties/testproperties/nestedprop/NestedProperties.java

I have also added a test util method to generated the list of compatible nested properties for setting then during development.

TCOMP-103 : added a way to assign recursively nested properties

---

daikon/src/main/java/org/talend/daikon/token/TokenGenerator.java
daikon/src/test/java/org/talend/daikon/token/TokenGeneratorTest.java

* Adds a token generator unique to the machine running the code.
* Compatible with Studio code for generating machine unique ids (with few improvements such as leveraging Java API iso. native command runs).
* Unit test for generator.

Machine token generator

---

daikon/src/main/java/org/talend/daikon/avro/SchemaConstants.java
daikon/src/main/java/org/talend/daikon/talend6/Talend6SchemaConstants.java

[TDKN-22] add isKey on SchemaConstant

[TDKN-22] add isKey on SchemaConstant

---

daikon/src/main/java/org/talend/daikon/properties/Property.java
daikon/src/main/java/org/talend/daikon/properties/PropertyFactory.java
daikon/src/test/java/org/talend/daikon/properties/PropertyFactoryTest.java
daikon/src/test/java/org/talend/daikon/properties/PropertyTest.java

[TDKN-23] Remove defaultValue from Property

[TDKN-23] Remove defaultValue from Property

---

daikon/src/main/java/org/talend/daikon/properties/Properties.java
daikon/src/test/java/org/talend/daikon/properties/PropertiesTest.java

Proposition of fix for the TDKN-44

TDKN-44: clear forms during serialize

---

daikon/src/main/java/org/talend/daikon/properties/Property.java

Fixed constant name in daikon.
I've not find this constant usage in components

Fixed I18N_PROPERTY_POSSIBLE_VALUE_PREFIX constant name

---

daikon/src/main/java/org/talend/daikon/properties/Properties.java
daikon/src/main/java/org/talend/daikon/properties/PropertiesDynamicMethodHelper.java
daikon/src/main/java/org/talend/daikon/properties/PropertiesImpl.java
daikon/src/main/java/org/talend/daikon/properties/property/Property.java
daikon/src/test/java/org/talend/daikon/properties/PropertiesTest.java
daikon/src/test/java/org/talend/daikon/properties/PropertiesVisitorTest.java
daikon/src/test/java/org/talend/daikon/properties/presentation/FormTest.java
daikon/src/test/java/org/talend/daikon/properties/test/PropertiesTestUtils.java
daikon/src/test/java/org/talend/daikon/properties/testproperties/PropertiesWithDefinedI18N.java
daikon/src/test/java/org/talend/daikon/properties/testproperties/TestProperties.java
daikon/src/test/java/org/talend/daikon/properties/testproperties/nestedprop/NestedNestedProperties.java
daikon/src/test/java/org/talend/daikon/properties/testproperties/nestedprop/NestedProperties.java
daikon/src/test/java/org/talend/daikon/properties/testproperties/references/ConnectionProperties.java
daikon/src/test/java/org/talend/daikon/properties/testproperties/references/ModuleConnectionProperties.java
daikon/src/test/java/org/talend/daikon/properties/testproperties/references/MultipleRefProperties.java

I am not happy with this implementation and would like some advice.
there are too many instanceof ifs in this.

TCOMP-200 : make Properties an interface - temporary commit

---

daikon/src/main/java/org/talend/daikon/properties/service/PropertiesServiceImpl.java
daikon/src/test/java/org/talend/daikon/properties/service/PropertiesServiceTest.java

I made the callback service impl and interface work with properties so that Components use will be also Properties instead of ComponentProperties.

TCOMP-201 : make prop service not generic anymore.

---

daikon/src/main/java/org/talend/daikon/avro/SchemaConstants.java

Related to 
https://jira.talendforge.org/browse/TDKN-65
https://jira.talendforge.org/browse/TUP-4863
I didn't find better than GENERATED name.

TDKN-65 Added TALEND_FIELD_GENERATED constant to SchemaConstants

---

daikon/src/main/java/org/talend/daikon/properties/property/Property.java
daikon/src/test/java/org/talend/daikon/properties/PropertyTest.java

https://jira.talendforge.org/browse/TDI-36463

TDI-36463: Add change property required method

---

daikon/src/main/java/org/talend/daikon/di/DiOutgoingSchemaEnforcer.java
daikon/src/test/java/org/talend/daikon/di/DiOutgoingSchemaEnforcerTest.java

https://jira.talendforge.org/browse/TUP-4932

TUP-4932: Fixed date type convert issue

---

LICENSE
daikon/README.md

[![Review](http://beta.codenvy.com/factory/resources/codenvy-review.svg)](http://beta.codenvy.com/f?id=essb0syccun7iff6)
:dizzy:

Added an Apache V2  LICENSE file

---

daikon/src/main/java/org/talend/daikon/properties/presentation/Widget.java

TUP-5101: Make Widget of TEXT_AREA available in new framework

TUP-5101: Make Widget of TEXT_AREA available in new framework

---

daikon/src/main/java/org/talend/daikon/properties/presentation/Widget.java

TUP-5252: add json table widget type.

TUP-5252: add json table widget type.

---

README.md

Just a few small missing characters, upper vs. lower case and removal of unnecessary words.

Fix typos & formatting

---

daikon-service/pom.xml
daikon-service/service-examples/weather-service/src/main/java/org/talend/daikon/example/WeatherServiceImpl.java
daikon-service/service-parent/pom.xml

* upgrade to spring-boot 1.4.1-RELEASE
* remove unnecessary references to REST in WeatherServiceImpl
* update forbidden dependencies to let org.codehaus.jackson* from avro

feat (TCOMP-262): enable datatore rest endpoint

---

daikon/src/main/java/org/talend/daikon/exception/ExceptionContext.java
daikon/src/main/java/org/talend/daikon/exception/TalendRuntimeException.java
daikon/src/main/java/org/talend/daikon/exception/error/CommonErrorCodes.java
daikon/src/main/java/org/talend/daikon/exception/json/JsonErrorCode.java
daikon/src/test/java/org/talend/daikon/exception/TalendRuntimeExceptionTest.java
daikon/src/test/java/org/talend/daikon/exception/json/JsonErrorCodeTest.java

to create a complete exception you need to do this
```
TalendRuntimeException exception = new TalendRuntimeException(
UNEXPECTED_ARGUMENT, rootCauseException,
ExceptionContext.build().put("argument", "Value 1").put("value", "123");
```
A new exception builder is introduced to make the wrtting of TalendRuntimeException simpler.
```
TalendRuntimeException exception = TalendRuntimeException.build(
UNEXPECTED_ARGUMENT, rootCauseException).set("Value 1", "123");
```
put can still be used but this is not compulsory. This avoid replicating the key everywhere and make is simpler to write …

Tdkn 55 improve exceptions

---

daikon/src/main/java/org/talend/daikon/properties/property/EnumListProperty.java

use sun class ParameterizedTypeImpl
change to java API ParameterizedType

fix(TDKN-81) : avoid import sun class

---

daikon/src/main/java/org/talend/daikon/serialize/jsonschema/JsonPropertiesResolver.java
daikon/src/test/java/org/talend/daikon/properties/TestEmptyProperties.java
daikon/src/test/java/org/talend/daikon/serialize/jsonschema/JsonSchemaUtilTest.java

Keep the default value when you do not have a Property or a Properties.
Fix NullPointerException on missing Properties.

fix(TDKN-94): Fix deserialization of an empty JSON

---

daikon-spring/pom.xml
pom.xml

spring was 4.2 and Junit was 4.11
updated the spring version to match the one used in https://github.com/Talend/components
spring now is 4.3.3 and Junit was 4.12

fix (TCOMP-330): update spring version to match API rest

---

daikon/src/main/java/org/talend/daikon/serialize/jsonschema/PropertyTrigger.java
daikon/src/main/java/org/talend/daikon/serialize/jsonschema/UiSchemaConstants.java
daikon/src/main/java/org/talend/daikon/serialize/jsonschema/UiSchemaGenerator.java

Create a PropertyTrigger enum for ui-schema triggers instead of String constants

---

daikon/src/main/java/org/talend/daikon/java8/Consumer.java
daikon/src/main/java/org/talend/daikon/java8/Function.java
daikon/src/main/java/org/talend/daikon/java8/SerializableConsumer.java
daikon/src/main/java/org/talend/daikon/java8/SerializableFunction.java
daikon/src/main/java/org/talend/daikon/java8/Supplier.java

Updating the daikon interfaces that duplicate java 8 functions.

fix: Add a stand-in interface for the java8 Consumer function.

---

daikon/src/main/java/org/talend/daikon/di/DiOutgoingSchemaEnforcer.java

- [] The new code does not introduce new technical issues (sonar / eslint)
https://jira.talendforge.org/browse/TDKN-105
Test passes in California

TDKN-105 DISchemaEnforcer test does not pass in Pacific time zone

---

daikon/src/main/java/org/talend/daikon/avro/NameUtil.java
daikon/src/test/java/org/talend/daikon/avro/NameUtilTest.java

https://jira.talendforge.org/browse/TDKN-101
https://jira.talendforge.org/browse/TDKN-101

fix(TDKN-101): Move NameUtil from components to Daikon

---

daikon/src/main/java/org/talend/daikon/avro/AvroUtils.java
daikon/src/test/java/org/talend/daikon/avro/AvroUtilsTest.java

add a new method only
https://jira.talendforge.org/browse/TCOMP-379

fix(TCOMP-379): add a new method to check if the schema is empty

---

daikon/src/main/java/org/talend/daikon/avro/AvroUtils.java
daikon/src/test/java/org/talend/daikon/avro/AvroUtilsTest.java

AvroUtils.createEmptySchema() now is available
Related to https://jira.talendforge.org/browse/TCOMP-230

feat(TCOMP-230): add createEmptySchema method and unit test for it

---

daikon/src/main/java/org/talend/daikon/properties/presentation/Widget.java

feat(TDKN-117):add directory widget type

---

daikon/src/main/java/org/talend/daikon/sandbox/SandboxInstanceFactory.java

fix(fileio): Remove unused instanciation.

---

daikon/pom.xml

(TDKN-119) Uses Avro 1.8.0
Uses Avro 1.8.1

fix(TDKN-119): Update avro libraries to 1.8.1

---

daikon/src/main/java/org/talend/daikon/avro/AvroUtils.java
daikon/src/test/java/org/talend/daikon/avro/AvroUtilsTest.java

I added some util methods to AvroUtils. It will help me on processing component to easily support repetitive tasks.
The main improvement came from the "createRejectSchema" method, that normalize the processing of the reject schema. This is currently done in every component and has to be place in DAIKON.

feat(TFD-168): Add method on AvroUtils to have ease schema usage.

---

daikon/src/test/java/org/talend/daikon/properties/PropertiesTest.java
daikon/src/test/java/org/talend/daikon/properties/PropertyTest.java
daikon/src/test/java/org/talend/daikon/properties/service/PropertiesServiceTest.java
daikon/src/test/java/org/talend/daikon/properties/test/PropertiesTestUtils.java
daikon/src/test/java/org/talend/daikon/serialize/FullExampleProperties.java
daikon/src/test/java/org/talend/daikon/serialize/jsonschema/JsonSchemaUtilTest.java
daikon/src/test/java/org/talend/daikon/serialize/jsonschema/JsonWidgetTest.java

Try to fix codacy pendantic review by removing some "error prone" errors.

style(codacity): remove some "error prone" errors.

---

daikon/src/main/java/org/talend/daikon/properties/property/PropertyFactory.java
daikon/src/test/java/org/talend/daikon/properties/PropertyFactoryTest.java

Add a two new method on PropertyFactory to support list of String and list of unknown elements.
The list of String will be the most used type of list we are going to use, so adding a specific factory is a nice syntactic sugar.

feat(TFD-472): Add List Property into PropertyFactory to support list of string

---

daikon/src/main/java/org/talend/daikon/di/DiIncomingSchemaEnforcer.java
daikon/src/main/java/org/talend/daikon/i18n/I18nMessageProvider.java
daikon/src/main/java/org/talend/daikon/sandbox/SandboxedInstance.java
daikon/src/main/java/org/talend/daikon/serialize/SerializerDeserializer.java
daikon/src/test/java/org/talend/daikon/properties/PropertiesVisitorTest.java
daikon/src/test/java/org/talend/daikon/properties/service/PropertiesServiceTest.java
daikon/src/test/java/org/talend/daikon/properties/testproperties/TestProperties.java
daikon/src/test/java/org/talend/daikon/sandbox/SandboxInstanceFactoryTest.java
daikon/src/test/java/org/talend/daikon/serialize/FullExampleProperties.java
daikon/src/test/java/org/talend/daikon/serialize/jsonio/PersistenceTestObject.java
daikon/src/test/java/org/talend/daikon/serialize/jsonio/PersistenceTestObjectInner2.java
daikon/src/test/java/org/talend/daikon/serialize/jsonio/SerializeDeserializeTest.java

style(codacy): continue improving code quality.

---

README.md
pom.xml
reporting/pom.xml
ruleset.xml

Code coverage report remains in individual modules
all modules coverage reports are aggregated into on single file and they are sent to codacy for analysis and reporting.

chore(codacy):add aggregate module and send report to codacy

---

daikon/src/test/java/org/talend/daikon/avro/SampleSchemas.java

We frequently create sample Avro schemas that our components should be able to handle.
A tool SampleSchemas is provided with a list of Schemas that should be investigated as inputs into components.

feat(TFD-447): Add reusable sample schemas for testing.

---

daikon/src/main/java/org/talend/daikon/serialize/jsonschema/JsonSchemaGenerator.java

feat(TDKN-127): Better support for invalid cases.

---

daikon-service/pom.xml
daikon-service/service-parent/pom.xml
daikon/README.md
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [master]

---

daikon-service/pom.xml
daikon-service/service-parent/pom.xml
daikon/README.md
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.15]

---

daikon-service/pom.xml
daikon-service/service-parent/pom.xml
daikon/README.md
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.14]

---

pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.12]

---

daikon-service/pom.xml
daikon/README.md
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.13]

---

pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.2.0]

---

pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.4.0]

---

pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.5.0]

---

pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.6]

---

pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.8]

---

daikon/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.1.0]

---

daikon-service/pom.xml
daikon-service/service-parent/pom.xml
daikon/README.md
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [service_version_upgrade]

---

daikon-content-service/content-service-common/src/main/java/org/talend/daikon/content/AbstractResourceResolver.java
daikon-content-service/content-service-common/src/main/java/org/talend/daikon/content/ContentServiceImpl.java
daikon-content-service/content-service-common/src/main/java/org/talend/daikon/content/ResourceResolver.java
daikon-content-service/content-service-common/src/main/java/org/talend/services/ContentService.java
daikon-content-service/content-service-common/src/test/java/org/talend/daikon/content/ContentServiceImplTest.java
daikon-content-service/content-service-common/src/test/java/org/talend/daikon/content/DeletableLoaderResourceTests.java
daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalContentServiceConfiguration.java
daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalDeletableResource.java
daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalResourceResolver.java
daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ContentServiceConfiguration.java
daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ResourceResolver.java
daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/TestConfiguration.java

: improve first content service implementation :
* DeletablePathResolver --> ResourceResolver
* ContentServiceImpl 100% covered by unit tests

feat(content_service_improvement)

---

daikon-content-service/content-service-common/src/main/java/org/talend/daikon/content/ContentServiceImpl.java

[Fix] Don't enable ContentService if no resource loader found.

---

daikon/src/main/java/org/talend/daikon/avro/LogicalTypeUtils.java
daikon/src/test/java/org/talend/daikon/avro/LogicalTypeUtilsTest.java

Add utility class for Logical types
https://jira.talendforge.org/browse/TDKN-150

feat(TDKN-150): add LogicalTypeUtils class

---

daikon/src/main/java/org/talend/daikon/avro/LogicalTypeUtils.java
daikon/src/test/java/org/talend/daikon/avro/LogicalTypeUtilsTest.java

add getLogicalTypeName() method to LogicalTypeUtils
related to https://jira.talendforge.org/browse/TDKN-155

feat(TDNK-155): add etLogicalTypeName() method to LogicalTypeUtils

---

daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/AmazonS3TestWrapper.java

Need to expose test class for tests for tests in EE Daikon.
* Expose utility class AmazonS3TestWrapper for EE multi tenancy tests.

feat(TDP-3377 TDP-3385): Need to expose test class for tests

---

daikon/src/main/java/org/talend/daikon/SimpleNamedThing.java
daikon/src/main/java/org/talend/daikon/i18n/tag/DefinitionTag.java
daikon/src/main/java/org/talend/daikon/i18n/tag/HasTags.java
daikon/src/main/java/org/talend/daikon/i18n/tag/Tag.java
daikon/src/main/java/org/talend/daikon/i18n/tag/TagImpl.java
daikon/src/main/java/org/talend/daikon/i18n/tag/TranslatableTaggedImpl.java
daikon/src/main/java/org/talend/daikon/properties/PropertiesImpl.java
daikon/src/test/java/org/talend/daikon/i18n/tag/CommonTestTags.java
daikon/src/test/java/org/talend/daikon/i18n/tag/TagImplTest.java
daikon/src/test/java/org/talend/daikon/i18n/tag/TranslatableTaggedImplTest.java
daikon/src/test/resources/org/talend/daikon/i18n/tag/CommonTestTags.properties
daikon/src/test/resources/org/talend/daikon/i18n/tag/TagImplTest.properties
daikon/src/test/resources/org/talend/daikon/i18n/tag/TranslatableTaggedImplTest.properties

* Add tags to daikon
Add tags implementation in daikon. Current implementation supports hierarchical tags, tags internationalization.

feat(TCOMP-276): add endpoints search by tags

---

daikon/src/main/java/org/talend/daikon/avro/AvroRegistry.java

Deprecate AvroRegistry class usage. This is a quick fix to make developers aware of future changes
Related https://jira.talendforge.org/browse/TDKN-153

refactor(TDKN-153): deprecate AvroRegistry

---

daikon-spring/daikon-spring-security/pom.xml
daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/access/AccessDeniedDefaults.java
daikon-spring/daikon-spring-security/src/test/java/org/talend/daikon/security/access/RequiresAuthorityAspectTest.java
daikon/src/main/java/org/talend/daikon/exception/error/CommonErrorCodes.java

* Add defaults for empty Stream.
* Change AccessDeniedException in case of denied access for a HTTP 403.

chore: Minor improvements for daikon-spring-security

---

daikon/src/main/java/org/talend/daikon/properties/presentation/Widget.java
daikon/src/main/java/org/talend/daikon/serialize/jsonschema/UiSchemaConstants.java
daikon/src/main/java/org/talend/daikon/serialize/jsonschema/UiSchemaGenerator.java
daikon/src/test/java/org/talend/daikon/properties/presentation/WidgetTest.java
daikon/src/test/java/org/talend/daikon/serialize/jsonschema/UiSchemaGeneratorTest.java

feat (TDKN-136): add autofocus option

---

daikon/src/test/java/org/talend/daikon/token/TokenGeneratorTest.java

TokenGeneratorTest fails on Win machine
TokenGeneratorTest passes on Win machine
Related to https://jira.talendforge.org/browse/TDKN-118

fix(TDKN-118): fix TokenGeneratorTest

---

daikon/src/main/java/org/talend/daikon/avro/inferrer/SchemaInferrer.java

In many places we implement "infer schema" feature, which discovers Avro schema from data sample. For the moment there is only AvroRegistry.inferSchema() method dedicated to this functionaliry. This method is a little bit overkill. AvroRegistry class is supposed to share implementation of some features between parts of the system. But often we don't need/want to share schema inferring feature. Also AvroRegistry class has complicated implementation, which makes difficult to use it, understand what is going on, test and debug. 
So, it was decided to create separate interface for schema inferring, which is not …

feat(TDKN-173): add SchemaInferrer interface

---

daikon/src/main/java/org/talend/daikon/properties/presentation/Widget.java
daikon/src/main/java/org/talend/daikon/serialize/jsonschema/UiSchemaConstants.java

No widget type to handle code format.
New widget type to handle code format.
https://jira.talendforge.org/browse/TFD-1661

feat(TFD-1661): Add new widget type to handle code format

---

daikon/src/main/java/org/talend/daikon/avro/converter/JsonGenericRecordConverter.java
daikon/src/main/java/org/talend/daikon/avro/inferrer/JsonSchemaInferrer.java
daikon/src/test/java/org/talend/daikon/avro/converter/JsonGenericRecordConverterTest.java
daikon/src/test/java/org/talend/daikon/avro/inferrer/JsonSchemaInferrerTest.java

The schema inference doesn't support boolean type.
The schema inference supports boolean type.
https://jira.talendforge.org/browse/TFD-1745

feat(TFD-1745): Schema inference supports boolean type

---

daikon/src/main/java/org/talend/daikon/avro/inferrer/JsonSchemaInferrer.java

No name attribute for hierarchical and array field record.
Add name attribute for hierarchical and array field record.

feat(TFD-1713): Add name attribute for hierarchical and array field record

---

daikon-service/pom.xml
daikon-service/service-parent/pom.xml
pom.xml

chore(build): Specify snapshot and release repositories

---

daikon/src/main/java/org/talend/daikon/properties/Properties.java
daikon/src/main/java/org/talend/daikon/properties/PropertiesImpl.java
daikon/src/main/java/org/talend/daikon/serialize/SerializerDeserializer.java
daikon/src/test/java/org/talend/daikon/serialize/migration/ChildProperties.java
daikon/src/test/java/org/talend/daikon/serialize/migration/ParentProperties.java
daikon/src/test/java/org/talend/daikon/serialize/migration/PropertyMigrationTest.java

Post deserialization of nested properties is not working
Collect the post deserialization handler correctly 
https://jira.talendforge.org/browse/TDKN-177

fix(TDKN-177): fix nested properties post deserialization

---

daikon-spring/daikon-spring-mongo/README.MD
daikon-spring/daikon-spring-mongo/pom.xml
daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/CachedMongoClientProvider.java
daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/SimpleMongoClientProvider.java
daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/CachedMongoClientProviderTest.java

Use map with expiration (automatic eviction of clients after idle time of 10 minutes).
https://jira.talendforge.org/browse/TDKN-180

fix(TDKN-180) Provide cache-based MongoClientProvider

---

daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/api/TqlBuilder.java

The Tql Java API is not accessible as methods are package local 
Make them public
https://jira.talendforge.org/browse/TDS-2465

feat(TDS-2465): make tql Java API public

---

daikon-spring/daikon-spring-tenancy/README.MD
daikon-spring/daikon-spring-tenancy/pom.xml
daikon-spring/daikon-spring-tenancy/src/main/java/org/talend/tenancy/DefaultForAll.java
daikon-spring/daikon-spring-tenancy/src/main/java/org/talend/tenancy/ForAll.java
daikon-spring/daikon-spring-tenancy/src/test/java/org/talend/tenancy/DefaultForAllTest.java
daikon-spring/pom.xml

https://jira.talendforge.org/browse/TDP-4337
* Add module for multi tenancy support code.
* Add default implementation for non-multi tenant execution.

chore(TDP-4337): Add new module for Spring related multi-tenancy

---

daikon/src/main/java/org/talend/daikon/converter/LocalDateConverter.java

fix: Typo in comment.

---

daikon-audit/src/main/java/org/talend/logging/audit/impl/ProxyEventAuditLogger.java
daikon-audit/src/test/java/org/talend/logging/audit/impl/EventAuditLoggerTest.java

Trying to record an event which was declared without parameters causes NPE.

Fixed NPE which happens if event is declared without parameters

---

daikon-i18n/README.adoc
daikon-i18n/pom.xml
daikon-i18n/src/main/java/org/talend/daikon/i18n/BaseBundle.java
daikon-i18n/src/main/java/org/talend/daikon/i18n/BaseControl.java
daikon-i18n/src/main/java/org/talend/daikon/i18n/BaseProvider.java
daikon-i18n/src/main/java/org/talend/daikon/i18n/ComponentResourceBundleControlProvider.java
daikon-i18n/src/main/java/org/talend/daikon/i18n/MapBundle.java
daikon-i18n/src/main/java/org/talend/daikon/i18n/ProviderLocator.java
daikon-i18n/src/main/resources/META-INF/services/java.util.spi.ResourceBundleControlProvider
daikon-i18n/src/test/java/org/talend/daikon/i18n/ComponentResourceBundleControlProviderTest.java
pom.xml

Ability to load resource bundle resources from anywhere without modifying the API.
Java 8 ResourceBundleControlProvider

adding i18n loader module (proposal)

---

daikon-multitenant/multitenant-core/src/main/java/org/talend/daikon/multitenant/datasource/TenantAwareDataSource.java
daikon-multitenant/multitenant-spring-async/src/main/java/org/talend/daikon/multitenant/async/TenancyContextPropagationConfiguration.java

fix(tenancy): use optional tenant to avoid NPE at runtime

---

daikon-multitenant/multitenant-core/pom.xml

e.g. https://jira.talendforge.org/browse/TDQ-14597

chore(TDQ-14597): build multitenant-core with BND tool

---

pom.xml

adding autoVersionSubmodules to release plugin

---

pom.xml

SCM meta are wrong breaking mvn release plugin
Fill the required info.

fixing scm information

---

daikon/pom.xml

jackson 1.9.13 used by avro has security issues 
those "known" issues are fixed with 1.9.14-TALEND
https://jira.talendforge.org/browse/TDKN-193>

chore(TDKN-193):change jackson 1.9.13 to 1.9.14-TALEND

---

daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/Log4j2JSONLayout.java
daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/LogbackJSONLayout.java

This PR fixes concurrent modification exception in logging-event-layout.

bugfix(logging): fixed concurrent modification error in logging event layout

---

daikon/src/main/java/org/talend/daikon/runtime/RuntimeUtil.java
daikon/src/test/java/org/talend/daikon/runtime/RuntimeUtilTest.java

https://jira.talendforge.org/browse/TDI-40061

fix(TDI-40061): avoid to reset the url factory

---

daikon-logging/logging-kafka-interceptor/src/test/java/org/talend/daikon/logging/kafka/ConsumerInterceptorsTest.java
daikon-logging/logging-kafka-interceptor/src/test/java/org/talend/daikon/logging/kafka/ProducerInterceptorsTest.java

Avoid to throw class cast exception in the interceptor
Use  byte[] for the message

Update Logging Kafka Unit tests to use byte[] for the message

---

daikon-tql/daikon-tql-core/pom.xml
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/AndExpression.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/ComparisonExpression.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/ComparisonOperator.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldBetweenExpression.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldCompliesPattern.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldContainsExpression.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldInExpression.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldIsEmptyExpression.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldIsInvalidExpression.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldIsValidExpression.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldMatchesRegex.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldReference.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/LiteralValue.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/NotExpression.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/OrExpression.java
daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/model/TestTqlElement.java

 chore(TDS-2298): equals method for tql objects

---

daikon-spring/daikon-spring-zipkin/pom.xml
daikon-spring/daikon-spring-zipkin/src/main/java/org/talend/daikon/zipkin/HistoryZipkinKafkaSenderConfiguration.java
daikon-spring/daikon-spring-zipkin/src/main/java/org/talend/daikon/zipkin/ZipkinKafkaSenderConfiguration.java
daikon-spring/pom.xml

See https://jira.talendforge.org/browse/TDKN-200
See https://jira.talendforge.org/browse/TDKN-200
https://jira.talendforge.org/browse/TDKN-200

chore(TDKN-200): Add new project daikon-spring-zipkin

---

daikon-logging/logging-kafka-interceptor/pom.xml
daikon-logging/logging-kafka-interceptor/src/main/java/org/talend/daikon/logging/TalendKafkaConsumerInterceptor.java
daikon-logging/logging-kafka-interceptor/src/main/java/org/talend/daikon/logging/TalendKafkaProducerInterceptor.java
daikon-logging/logging-kafka-interceptor/src/test/java/org/talend/daikon/logging/kafka/ConsumerInterceptorsTest.java
daikon-logging/logging-kafka-interceptor/src/test/java/org/talend/daikon/logging/kafka/ProducerInterceptorsTest.java

The existing kafka logging won't work with Avro
Adapt kafka logging message for Avro

Adapt kafka logging message for Avro

---

daikon-content-service/content-service-journal-mongo/pom.xml
daikon-content-service/content-service-journal-mongo/src/main/java/org/talend/daikon/content/journal/MongoResourceJournalResolver.java
daikon-content-service/content-service-journal-mongo/src/test/java/org/talend/daikon/content/journal/MongoResourceJournalResolverTest.java
daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/JournalizedResourceResolver.java
daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/ResourceJournal.java
daikon-multitenant/multitenant-core/src/main/java/org/talend/daikon/multitenant/context/MultiTenantRunnable.java
daikon-multitenant/multitenant-core/src/test/java/org/talend/daikon/multitenant/context/MultiTenantRunnableTest.java

* Add utility class for multi tenant runnable.
* Use multi tenancy wrapped runnable during sync.

fix(TDKN-201): Fix missing tenancy context propagation during sync

---

daikon-logging/logging-event-layout/README.MD

logging attributes *application* and *service* descriptions are not very precise
add more details on the logging *application* and *service* attributes

doc(logging): update logging read, precise app and service attributes

---

daikon-logging/logging-event-layout/README.MD

logging attributes *application* and *service* descriptions are not very precise
add more details on the logging *application* and *service* attributes

logging readme update

---

daikon-content-service/content-service-journal-mongo/src/main/java/org/talend/daikon/content/journal/MongoResourceJournalResolver.java
daikon-content-service/content-service-journal-mongo/src/test/java/org/talend/daikon/content/journal/MongoResourceJournalResolverTest.java

We have some issue when we try to delete cache using regexp
Clean pattern before Mongo request 
https://jira.talendforge.org/browse/TDP-5813

fix(TDP-5813): Bad Mongo pattern for clean cache

---

daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/BeanPredicateVisitor.java
daikon-tql/daikon-tql-bean/src/test/java/org/talend/tql/bean/BeanPredicateVisitorTest.java
daikon-tql/daikon-tql-core/src/main/antlr4/TqlLexer.g4
daikon-tql/daikon-tql-core/src/main/antlr4/TqlParser.g4
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/api/TqlBuilder.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldContainsExpression.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/parser/TqlExpressionVisitor.java
daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/TestTqlParser_AllFields.java
daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/TestTqlParser_Complex.java
daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/TestTqlParser_Contain.java
daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/api/TestTqlApi_ContainsIgnoreCase.java
daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/model/TestTqlElement.java
daikon-tql/daikon-tql-mongo/src/main/java/org/talend/tqlmongo/ASTVisitor.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_ContainsIgnoreCase.java

feat(TDS-669): add tql containsIgnoreCase operator

---

README.md
daikon-tql/README.md
daikon-tql/daikon-tql-client/src/converter/__tests__/parser.spec.js
daikon-tql/daikon-tql-client/src/converter/parser.js
daikon-tql/daikon-tql-core/src/main/resources/tql/index.js
daikon-tql/pom.xml

Some TQL listeners are missing after introducing new operators.
Implement those new TQL listeners.
https://jira.talendforge.org/browse/TDP-4404

fix(TDP-4404): missing tql javascript listener

---

daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_WordComply.java
daikon/src/main/java/org/talend/daikon/pattern/word/WordPatternToRegexConstants.java
daikon/src/test/java/org/talend/daikon/pattern/word/WordPatternToRegexTest.java

feat(TDQ-15761): Adapt word-based patterns and regexes

---

daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_WordComply.java

feat(TDS-2681): Add tests.

---

daikon-signature-verifier/pom.xml

* Add bundle package for studio integration.
https://jira.talendforge.org/browse/TESB-23714

fix(TESB-23714): Add bundle package for signature verifier

---

daikon-signature-verifier/pom.xml

* Add missing "bundle" packaging for studio integration (thx @Diya).
https://jira.talendforge.org/browse/TESB-23714

fix(TESB-23714): Add bundle package for signature verifier (2)

---

daikon-audit/audit-common/src/main/java/org/talend/logging/audit/StandardEventAuditLogger.java
daikon-audit/audit-common/src/test/java/org/talend/logging/audit/EventAuditLoggerTest.java

https://jira.talendforge.org/browse/TDKN-202

fix(TDKN-202): Add a dot to the end of message in daikon-audit

---

daikon-service/pom.xml
daikon-spring/daikon-spring-mongo/pom.xml
pom.xml

* Fix CVE for jackson version (2.9.4 -> 2.9.5)
https://jira.talendforge.org/browse/TDKN-204

fix(cumulative): Cumulative fixes for daikon

---

daikon-content-service/pom.xml
daikon-service/service-parent/pom.xml
pom.xml

also remove explicit declaration of maven-jar-plugin already
bound to jar and maven-plugin packaging
a bit of cleanup in pom 
* separate plugin declaration and configuration
* removing forced declaration of maven-jar-plugin

chore: separate plugin from plugin management

---

daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegexConstants.java
daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java

https://jira.talendforge.org/browse/TDQ-16037

fix(TDQ-16037): remove redundant curly braces in KANJI_RARE regex

---

daikon-messages/README.md
daikon-messages/messages-model/pom.xml
daikon-messages/messages-model/src/main/avro/MessageHeader.avsc
daikon-messages/messages-model/src/main/java/org/talend/daikon/messages/avro/DaikonRecordBase.java
daikon-messages/messages-model/src/main/java/org/talend/daikon/messages/avro/SecuredData.java
daikon-messages/messages-model/src/main/resources/org/talend/daikon/messages/enum.vm
daikon-messages/messages-model/src/main/resources/org/talend/daikon/messages/fixed.vm
daikon-messages/messages-model/src/main/resources/org/talend/daikon/messages/protocol.vm
daikon-messages/messages-model/src/main/resources/org/talend/daikon/messages/record.vm
daikon-messages/messages-model/src/test/java/org/talend/daikon/messages/header/TestMessageHeaderExtractor.java

See https://jira.talendforge.org/browse/TDKN-205.
* Prevent use of unfiltered toString() in generated classes.
* Add custom templates to change record super class with custom one.
https://jira.talendforge.org/browse/TDKN-205

fix(TDKN-205): Prevent using Avro default toString

---

Jenkinsfile

https://jira.talendforge.org/browse/TDKN-210

chore(TDKN-210): Add release notification

---

daikon-exception/pom.xml

https://jira.talendforge.org/browse/TDKN-213

WorkItem(TDKN-213):Daikon exception is not an OSGI plugin

---

Jenkinsfile

Failures due to attempting to pushing artifacts to the wrong Nexus URL
Correct the environment variable used in the pipeline to get the source branch of the PR.
https://jira.talendforge.org/browse/DEVOPS-6085

DEVOPS-6085 Fix Jenkins pipeline for PR builds

---

Jenkinsfile

A webhook has been added to this repository, need to remove polling 
Remove polling trigger 
None

Added repository webhook, remove polling

---

daikon/src/main/java/org/talend/daikon/pattern/character/CharPattern.java
daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegex.java
daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegexConstants.java
daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java

* feat(TDQ-16381): Split Latin in characters pattern
* feat(TDQ-16381): Add tests on accents in UT
We need to split usual latin characters (letters a to z) from rare latin characters (accents et al.)

feat(TDQ-16481): Split Latin in characters pattern (#438)

---

daikon-scala/dynamic-log/dynamic-log-web-play/pom.xml

This commit removes a duplicated dependency in one of the poms.

Removing duplicate dependency

---

daikon/src/main/java/org/talend/daikon/pattern/character/CharPattern.java
daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegex.java
daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegexConstants.java
daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java

* feat(TDQ-16381): Split Latin in characters pattern
* feat(TDQ-16381): Add tests on accents in UT

feat(TDQ-16481): Split Latin in characters pattern

---

Jenkinsfile

Allow release from all branches, allowing maintenance releases more easily.
(no jira)

chore(build): Allow release from branches

---

daikon-spring/daikon-spring-examples/daikon-spring-example-security/README.adoc
daikon-spring/daikon-spring-examples/daikon-spring-example-security/pom.xml
daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/java/org/talend/demo/actuator/ActuatorApplication.java
daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/java/org/talend/demo/actuator/ActuatorDemoController.java
daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/java/org/talend/demo/actuator/SecurityConfiguration.java
daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/resources/application-notoken.properties
daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/resources/application-token.properties
daikon-spring/daikon-spring-examples/pom.xml
daikon-spring/daikon-spring-security/README.adoc
daikon-spring/daikon-spring-security/pom.xml
daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/access/AccessDeniedDefaults.java
daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/access/RequiresAuthority.java
daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/access/RequiresAuthorityAspect.java
daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/NoConfiguredTokenFilter.java
daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenAuthentication.java
daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenAuthenticationFilter.java
daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java
daikon-spring/daikon-spring-security/src/main/resources/META-INF/spring.factories
daikon-spring/daikon-spring-security/src/test/java/org/talend/daikon/security/access/RequiresAuthorityAspectTest.java
daikon-spring/daikon-spring-security/src/test/java/org/talend/daikon/security/token/NoConfiguredTokenFilterTest.java
daikon-spring/daikon-spring-security/src/test/java/org/talend/daikon/security/token/TokenAuthenticationFilterTest.java
daikon-spring/daikon-spring-security/src/test/java/org/talend/daikon/security/token/TokenAuthenticationTest.java
daikon-spring/pom.xml

See https://jira.talendforge.org/browse/TDKN-217 and relates to https://github.com/Talend/policies/pull/35
See https://jira.talendforge.org/browse/TDKN-217
https://jira.talendforge.org/browse/TDKN-217

chore(TDKN-217): Add token based authentication support

---

Jenkinsfile
daikon-documentation/pom.xml
daikon-documentation/src/main/java/org/talend/daikon/ReleaseNotes.java
daikon-documentation/src/test/java/org/talend/daikon/ReleaseNotesTest.java
daikon-documentation/src/test/resources/project-to-test/pom.xml
pom.xml
releases/pom.xml

When a release is performed, a AsciiDoc file should be generated in "/releases/<release version>.adoc". This file will contain at least:
* Release number
* All issues fixed grouped by type (Bug / Fix / Work item...)
https://jira.talendforge.org/browse/TDKN-211

chore(TDKN-211): Add release notes

---

daikon-logging/logging-event-layout/README.MD

Updates the readme.
The log correlation and custom field documentation was out of date with the behavior of LayoutUtils and LogbackJSONLayout.
See: https://github.com/Talend/platform-services-logging/blob/master/logstash/apps/kafka/conf/logstash_elasticsearch_system.conf#L31

Fix readme about log correlation and custom fields

---

daikon/src/main/java/org/talend/daikon/sandbox/properties/SunOracleStandardPropertiesStrategy.java

[TDKN-218] Ensure a missing SUN_BOOT_CLASS_PATH does not lead to a NPE in SunOracleStandardPropertiesStrategy

---

daikon-tql/daikon-tql-client/README.md

The readme mixes internal and external info and the package name is not mentioned.
Focus the main part of the readme on external info (how to use it).
And then add some random information I wished to have.

doc(TQL): Update client readme

---

daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/BeanPredicateVisitor.java
daikon-tql/daikon-tql-bean/src/test/java/org/talend/tql/bean/BeanPredicateVisitorTest.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/OrExpression.java

More stylistic issues than actual issues:
* Replace some loops with a Stream API usage.
* Rename "andExpressions" to "orExpression" in OrExpression.
* Remove not thrown exception in unit tests
Review style of code.
No jira.

chore(): Minor code style improvements in TQL -> Bean

---

daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AuditConfigurationMapImpl.java
daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AuditConfigurationMapImplTest.java
daikon/src/main/java/org/talend/daikon/sandbox/properties/SunOracleStandardPropertiesStrategy.java
pom.xml

* Fix format issues.
https://jira.talendforge.org/browse/TDKN-225

chore(TDKN-225): Move to Greenwich.SR1 for spring-cloud

---

daikon-content-service/content-service-journal-mongo/src/main/java/org/talend/daikon/content/journal/MongoResourceJournalResolver.java
daikon-content-service/content-service-journal-mongo/src/test/java/org/talend/daikon/content/journal/MongoResourceJournalResolverTest.java
daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/ResourceJournal.java
daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/ResourceResolverJournal.java
daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/configuration/JournalizedConfiguration.java

wi(TDKN-224): fix circular injection

---

daikon-spring/daikon-content-service/content-service-journal-mongo/src/main/java/org/talend/daikon/content/journal/MongoResourceJournalResolver.java
daikon-spring/daikon-content-service/content-service-journal-mongo/src/test/java/org/talend/daikon/content/journal/MongoResourceJournalResolverTest.java
daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/ResourceJournal.java
daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/ResourceResolverJournal.java
daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/configuration/JournalizedConfiguration.java

 wi(TDKN-224): fix circular injection

---

pom.xml

See https://jira.talendforge.org/browse/TDKN-228
See https://jira.talendforge.org/browse/TDKN-228
https://jira.talendforge.org/browse/TDKN-228

chores(TDKN-228) Update Guava version

---

daikon-documentation/src/main/java/org/talend/daikon/ReleaseNotes.java

add project name as optional parameter in the documentation

---

daikon/src/main/java/org/talend/daikon/number/BigDecimalParser.java
daikon/src/test/java/org/talend/daikon/number/BigDecimalParserTest.java

* add management of space separators
* fix space management of inferDecimalSeparator
* add TUs
* fix existing TUs
cherry pick of https://github.com/Talend/daikon/pull/483
https://jira.talendforge.org/browse/TDKN-233

fix(TDKN-233): manage more use cases in BigDecimalParser (#483)

---

daikon-spring/daikon-content-service/content-service-journal-mongo/pom.xml
daikon-tql/daikon-tql-mongo/pom.xml
daikon-tql/daikon-tql-mongo/src/main/java/org/talend/tqlmongo/ASTVisitor.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Abstract.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Between.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Boolean.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Complex.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Comply.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Contain.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_ContainsIgnoreCase.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Decimal.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_FieldComparison.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_In.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Integer.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Match.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Not.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_WordComply.java
pom.xml

chore(TDS-3833): make daikon tql compatible with spring data mongodb 2

---

daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/CipherSources.java
daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/CipherSourcesTest.java

add blowfish as a supported encryption method
add dedicated method
https://jira.talendforge.org/browse/TDQ-14200

workItem(TDQ-14200) : add blowfish encryption method

---

daikon-spring/daikon-content-service/s3-content-service/pom.xml
daikon-spring/daikon-spring-metrics/pom.xml
pom.xml

Dependencies listed in TDKN-240 needs update.
Update outdated dependencies.
* Commons-io (1.3.2 -> 2.6)
* Ensure all modules correctly take "commons-io:commons-io" as dependency.
* Guava update (25.1-jre -> 27.1-jre).
https://jira.talendforge.org/browse/TDKN-240

fix(TDKN-240): Upgrade dependencies

---

daikon-tql/daikon-tql-mongo/pom.xml
daikon-tql/daikon-tql-mongo/src/main/java/org/talend/tqlmongo/ASTVisitor.java
pom.xml

TDS team needs a fix from Spring Boot 2.1.4 (https://jira.spring.io/browse/DATACMNS-1438).
* Upgrade Spring Boot (2.1.1 -> 2.1.4)
* Review way to import Spring Data mongo for `daikon-tql-mongo` (should rely only on Spring Boot version, not Spring Data)
* Minor import issue fix in ASTVisitor (use Apache commons StringUtils iso. Spring's).
https://jira.talendforge.org/browse/TDKN-241

chore(TDKN-241) Upgrade to Spring Boot 2.1.4

---

daikon-spring/daikon-spring-examples/pom.xml

* Examples still run on Spring Boot 2.1.1
* Upgrade Spring Boot version for examples (2.1.1 -> 2.1.4). 
https://jira.talendforge.org/browse/TDKN-241

chore(TDKN-241): Upgrade Spring Boot version for examples.

---

pom.xml

Update Jackson to version 2.9.8 used by all the products (not done yet on 0.31 now)
https://jira.talendforge.org/browse/TDKN-242

fix(TDKN-242) update jackson version to 2.9.8

---

pom.xml

Update Jackson to version 2.9.9
https://jira.talendforge.org/browse/TDKN-242

fix(TDKN-242) update jackson version to 2.9.9

---

daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/CipherSources.java
daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/CipherSourcesTest.java

the default Blowfish encryption mode is not secured.
change the encryption mode to CBC

feat(TDQ-14200) : add CBC mode to Blowfish encryption

---

daikon-spring/daikon-spring-examples/daikon-spring-example-security/README.adoc
daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/java/org/talend/demo/actuator/ActuatorDemoController.java
daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/java/org/talend/demo/actuator/SecurityConfiguration.java
daikon-spring/daikon-spring-security/README.adoc
daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenProtectedPath.java
daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java

See https://jira.talendforge.org/browse/TDKN-244
* Allow to custom add token protected using `TokenProtectedPath` beans.
* Update to sample application.
* Documentation update.
https://jira.talendforge.org/browse/TDKN-244

feat(TDKN-244): Allow to custom add token protected endpoints 

---

daikon-audit/audit-logback/src/main/java/org/talend/logging/audit/logback/LogbackConfigurer.java

https://jira.talendforge.org/browse/TDI-42071
https://jira.talendforge.org/browse/TDI-42071

fix(TDI-42071): avoid the warn : No context given for ch.qos.logback.core.encoder.LayoutWrappingEncoder

---

daikon-spring/daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalDeletableResource.java
daikon-spring/daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalResourceResolver.java

In TDP we need to wrap LocalDeletableResource. In order to do that we need that class to be public 
Make this class public 

feat(): make LocalDeletableResource public 

---

daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/KeySourcesTest.java
daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/Log4j2JSONLayoutTest.java
daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java

Last minute fixes for 1.4.0 release:
* Code format.
* Fix too long key selected for AES encryption.
(no jira)

chore(build): Build fixes for 1.4.0 build

---

daikon-crypto/crypto-utils/README.md
daikon-crypto/crypto-utils/pom.xml
daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/CipherSources.java
daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/CipherSourcesTest.java
pom.xml

This task is to support specifying Provider objects in CipherSources.

TDKN-252 - Support specifying Provider objects in CipherSources

---

daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java

When several Spring Security Java configuration are present (several class extend WebSecurityConfigurerAdapter) a cycle dependency injection can occur on TokenSecurityConfiguration. 
Remove the bean that can cause the pb.
Chore
https://jira.talendforge.org/browse/TDP-7278 

Chore: fix cycle dependency injection

---

daikon-spring/daikon-content-service/content-service-common/pom.xml
daikon-spring/daikon-content-service/local-content-service/pom.xml
daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java

Some project import spring boot but only use spring-context functionnality
do not import spring boot when not necessary

feat(TDP-7278): do not import spring boot when not necessary

---

daikon-crypto/crypto-utils/pom.xml
pom.xml

Adds a OSGI bundle for crypto-utils module
Adds a OSGI bundle for crypto-utils module

kjwang/Fix (crypto-utils) Adds a OSGI bundle for crypto-utils module

---

pom.xml

We need to update Commons BeanUtils due to a cve - CVE-2019-10086

TDKN-258 - Update Commons BeanUtils

---

daikon-audit/audit-all/pom.xml
daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/Backends.java
daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/DefaultAuditLoggerBase.java
daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/Utils.java
daikon-audit/audit-log4j2/pom.xml
daikon-audit/audit-log4j2/src/main/java/org/talend/logging/audit/log4j2/Log4j2Backend.java
daikon-audit/audit-log4j2/src/main/java/org/talend/logging/audit/log4j2/Log4j2Configurer.java
daikon-audit/audit-log4j2/src/main/java/org/talend/logging/audit/log4j2/Log4j2HttpAppender.java
daikon-audit/audit-log4j2/src/test/java/org/talend/logging/audit/log4j2/Log4j2ConfigurerTest.java
daikon-audit/audit-log4j2/src/test/java/org/talend/logging/audit/log4j2/Log4j2HttpAppenderTest.java
daikon-audit/audit-log4j2/src/test/resources/configurer.audit.properties
daikon-audit/pom.xml
daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/Log4j2JSONLayout.java

support log4j2 for daikon audit
https://jira.talendforge.org/browse/TDI-43023
https://jira.talendforge.org/browse/TDI-43023

fix(TDI-43023): support log4j2 for daikon-audit

---

Jenkinsfile
pom.xml

fix(DEVOPS-7930): Fix branch build

---

daikon-bom/pom.xml
pom.xml

Simplify daikon version management.
Move bom from TSD to daikon.
https://jira.talendforge.org/browse/TSD-433

chore(TSD-433): add daikon bom

---

pom.xml

Some CVEs in current jackson version
Update Jackson to 2.10.0
https://jira.talendforge.org/browse/TDKN-263

TDKN-262 - Update Jackson to 2.10.0

---

daikon/src/main/java/org/talend/daikon/properties/PropertiesImpl.java
daikon/src/test/java/org/talend/daikon/properties/PropertiesTest.java

Main purpose of this PR is to enable PropertiesImpl to encrypt/decrypt StringProperty(ENCRYPT flag is set) by new algorithm.
Add following new method in PropertiesImpl which is supposed to be overridden by subclass.
protected void encryptData(Property property, boolean encrypt)
https://jira.talendforge.org/browse/TUP-24975
**Test Result**
`mvn -Dtest=PropertiesTest test `
```dProps
DEBUG [main] (PropertiesImpl.java:598) - Do not copy [Presentation Item: testPI - presItem.testPI.displayName]
[Property: aGreatProp3, Property: …
```

feat(TDI-42911) Remove CryptoHelper31

---

daikon/src/main/java/org/talend/daikon/properties/PropertiesImpl.java
daikon/src/test/java/org/talend/daikon/properties/PropertiesTest.java

Main purpose of this PR is to enable PropertiesImpl to encrypt/decrypt StringProperty(ENCRYPT flag is set) by new algorithm.
Add following new method in PropertiesImpl which is supposed to be overridden by subclass.
protected void encryptData(Property property, boolean encrypt)
https://jira.talendforge.org/browse/TUP-24975
**Local Test Results**
```
DEBUG [main] (PropertiesImpl.java:597) --- Do not copy [Presentation Item: testPI - presItem.testPI.displayName]
[Property: aGreatProp3, Property: aGreatProperty, Property: anotherProp, …
```

feat(TDI-42911) Remove CryptoHelper

---

daikon-logging/logging-event-layout/src/test/resources/log4j.xml
daikon-logging/logging-event-layout/src/test/resources/log4j2.xml
daikon-logging/logging-event-layout/src/test/resources/logback.xml
daikon-logging/logging-request-interceptor/pom.xml
daikon-logging/logging-request-interceptor/src/test/resources/logback-test.xml
daikon-multitenant/multitenant-spring-web/pom.xml
daikon-multitenant/pom.xml
daikon-spring/daikon-content-service/local-content-service/src/test/java/org/talend/daikon/content/local/LocalResourceResolverTest.java
daikon-spring/daikon-spring-examples/daikon-spring-example-metrics/pom.xml
daikon-spring/daikon-spring-examples/pom.xml
daikon-spring/daikon-spring-zipkin/pom.xml
daikon-spring/daikon-spring-zipkin/src/main/java/org/talend/daikon/zipkin/ZipkinKafkaSenderConfiguration.java
daikon/src/test/java/org/talend/daikon/avro/SchemaTest.java
daikon/src/test/java/org/talend/daikon/properties/PropertiesTest.java
daikon/src/test/resources/log4j.properties
pom.xml

Fix some outdated dependencies with an upgrade to latest available Spring 2.1.x.
Along Spring Boot upgrade (2.1.4 -> 2.1.10), add fixes and improvements:
* Remove remaining direct internal Spring version dependencies (rely only on Spring Boot BOM)
* Improve encrypted properties test to fully leverage crypto utils (no need to reimplement a KeySource)
* Fix local resource resolver not working on MacOS
* Remove some System.out in unit tests
* Move some unit test to INFO level (no need for DEBUG)
https://jira.talendforge.org/browse/TDKN-265
**[ ] This Pull Request introduces a breaking …

feat(TDKN-265): Upgrade to Spring Boot 2.1.10

---

pom.xml

Some CVEs in current jackson version
Update Jackson to 2.10.1
https://jira.talendforge.org/browse/TDKN-269

TDKN-269 - Update Jackson to 2.10.1

---

daikon-spring/daikon-spring-metrics/pom.xml
daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/LogTimed.java
daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/config/Aspects.java
daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/util/VariableLevelLog.java

See Jira 
Moving code from TDP to Daikon
https://jira.talendforge.org/browse/TDP-8039

feat(TDP-8039): Move LogTimed annotation to Daikon

---

daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/BeanPredicateVisitor.java
daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/DefaultLanguageBinder.java
daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/IterableMethodAccessor.java
daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/MapMethodAccessor.java
daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/MethodAccessorFactory.java
daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/UnaryMethodAccessor.java
daikon-tql/daikon-tql-bean/src/test/java/org/talend/tql/bean/BeanPredicateVisitorTest.java
daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/parser/Tql.java

MethodAccessor can manage args for the invoke method.

---

daikon-messages/messages-model-spring-support/src/main/java/org/talend/daikon/messages/spring/producer/MessageHeaderFactoryConfiguration.java
daikon-messages/messages-model/pom.xml
daikon-messages/messages-model/src/main/java/org/talend/daikon/messages/avro/SecuredData.java
daikon-messages/messages-model/src/main/java/org/talend/daikon/messages/utils/HeadersUtils.java
daikon-messages/messages-model/src/main/resources/org/talend/daikon/messages/enum.vm
daikon-messages/messages-model/src/main/resources/org/talend/daikon/messages/fixed.vm
daikon-messages/messages-model/src/main/resources/org/talend/daikon/messages/protocol.vm
daikon-messages/messages-model/src/main/resources/org/talend/daikon/messages/record.vm
daikon/pom.xml
daikon/src/main/java/org/talend/daikon/avro/inferrer/JsonSchemaInferrer.java
daikon/src/test/resources/org/talend/daikon/avro/visitor/record/optionalSimpleType_schema.json
pom.xml

Avro version are not the same on all daikon project.
Standardize avro version and upgrade it to the last Avro version 

feat(TDP-7886): standardize and upgrade Avro version

---

daikon-documentation/src/main/java/org/talend/daikon/finders/git/AbstractGitItemFinder.java

There is a NPE that occurs when you try to generate release notes for a project that does not have any previous release (no previous release tag).
Fix incorrect 'jump to root commit' when no release tag is yet present.
(no jira)

fix(release notes): Fix error when first release notes are generated

---

pom.xml

This task is to make sure we upgrade to commons-configuration2 due to CVE-2020-1953.

TDKN-279 - Upgrade commons-configuration2 to 2.7

---

daikon-spring/daikon-spring-examples/pom.xml
pom.xml

Need to update to latest Spring Boot 2.1.x
* Update Spring Boot to 2.1.13.RELEASE
* Update Spring Cloud to Greenwich SR5
* Update Jackson to 2.10.3
https://jira.talendforge.org/browse/TDKN-280

chore(TDKN-280): Prepare Daikon 2.1 version

---

daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/api/AuditContextFilter.java
daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/api/NoOpAuditContextFilter.java
daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogContextBuilder.java
daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogGenerationFilterImpl.java
daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/service/AuditLogGenerationFilterImplTest.java

https://jira.talendforge.org/browse/TPSVC-13814 

feat(TPSVC-13814): pass the response object into the context filter

---

daikon-spring/daikon-spring-audit-logs/README.adoc
daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditKafkaProperties.java
daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/model/AuditLogFieldEnum.java
daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/service/AuditLogContextBuilderTest.java

TPSVC-14118: Move audit logs JSON structure from snake case to camel case (backport)

---

daikon-audit/audit-common/src/main/java/org/talend/logging/audit/AuditLoggerFactory.java
daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AuditConfiguration.java
daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/Backends.java
daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/DefaultAuditLoggerBase.java
daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/Utils.java
daikon-audit/audit-common/src/test/java/org/talend/logging/audit/custom/AuditBackendMessage.java
daikon-audit/audit-common/src/test/java/org/talend/logging/audit/custom/CustomAuditBackend.java
daikon-audit/audit-common/src/test/java/org/talend/logging/audit/custom/CustomAuditBackendTest.java
daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AuditConfigurationTest.java

This PR allows daikon-audit users to dynamically instantiate a custom audit backend using configuration properties (it was previously only possible through the API).
This enables more flexibility, since it allows to switch backend dynamically (for example in DI jobs for Observability enterprise project).
This feature introduces a new type of backend to daikon-audit: "custom", and a new "backend class name" property, so that the audit backend can be dynamically specified using properties.
**Why introduce this feature in an 1.x branch?**
Because we need this feature for the Observability enterprise project, which has some impacts on DI jobs. Those jobs are currently using the …

feat(TDKN-288): Add new "custom audit backend" feature to daikon-audit

---

daikon-spring/daikon-spring-zipkin/src/main/java/org/talend/daikon/zipkin/ZipkinKafkaSenderConfiguration.java

feat(TDP-8780): Update ZipkinKafkaSenderConfiguration bean definition

---

daikon-audit/audit-log4j2/src/main/java/org/talend/logging/audit/log4j2/Log4j2Configurer.java

fix the log4j2
correct it
https://jira.talendforge.org/browse/TDI-44172

fix(TDI-44172): fix the log4j2 issue

---

daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ContentServiceConfiguration.java
daikon-spring/daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/S3ContentServiceConfigurationTest.java

(cherry picked from commit c7155dc952737c045ebb2d33e406372067946574)

fix: set the S3 bucket as a URL path for MINIO configuration (#622)

---

README.md
pom.xml

Follow library upgrades.
* Upgrade Spring Boot (2.2.5 -> 2.2.9)
* Upgrade Spring Cloud (Hoxton.SR3 -> Hoxton.SR6)
* Upgrade Jackson (2.10.3 -> 2.10.4)

chore(libs) Follow release train

---

pom.xml

Update Avro to the latest release.

fix(TDKN-292): Update Avro version to 1.10

---

daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogContextBuilder.java
daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSenderImpl.java
daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/api/AuditLogTest.java

https://jira.talendforge.org/browse/TPSVC-15254

TPSVC-15254: take the host from XFH header

---

daikon-audit/README.adoc
daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AbstractAuditLoggerBase.java
daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AbstractBackend.java
daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AbstractAuditLoggerBaseTest.java
daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AbstractBackendTest.java

A new proposal of how to integrate the TDKN-297 feature.
https://jira.talendforge.org/browse/TDKN-297

Pier co/chore/tdkn 297 disable message output

---

daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogContextBuilder.java

It has been spotted wrong ip issue in the audit logs generated by idaas.
Fixing the issue, I spotted a little issue in daikon-spring-audit-logs during request fields computation.
Fix the requst fields computation.
https://jira.talendforge.org/browse/TPSVC-15818

TPSVC-15818: [IDAAS] [AUDIT LOGS] Wrong IP - Fix request fields computation

---

daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogContextBuilder.java

TPSVC-15818: [IDAAS] [AUDIT LOGS] Wrong IP - Fix request fields computation (backport)

---

daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogContextBuilder.java

Requests to TMC WEB APP fails when X-Forwarded-Proto header is wrong
add aditional validation for scheme 
https://jira.talendforge.org/browse/TMC-22935

bug(TMC-22935) Can't set schedule to task,got " Failed to save schedule." 504 error

---

daikon-exception/pom.xml
daikon/pom.xml
pom.xml

This task is to update Jackson 1.9.13/14-TALEND to 1.9.15-TALEND, which has fixes for many recent CVEs.

TDKN-299 - Update Jackson 1.9.x to 1.9.15-TALEND

---

README.md
daikon-spring/daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/AmazonS3TestWrapper.java
pom.xml

* Upgrade to a newer version of Spring Boot (follow TSBI release train)
* Upgrade to Spring Boot 2.2.10 (2.2.9 -> 2.2.10)
* Upgrade to Hoxton.SR8 (Hoxton.SR6 -> Hoxton.SR8)

chore(update): Update Spring Boot version

---

daikon-documentation/pom.xml
daikon-logging/logging-event-layout/pom.xml
daikon-messages/messages-demo/pom.xml
daikon-scala/dynamic-log/dynamic-log-core/pom.xml
daikon/pom.xml
pom.xml

This task is to fix high/critical CVE issues in Daikon:
Plexus Utils 3.0.22
Commons Compress 1.18
Snakeyaml 1.25
Zookeeper 3.4.8
Netty 3.7.0
Logback Classic 1.1.7

TDKN-300 - Fix critical/high CVE issues

---

daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/SimpleAuditLoggerBase.java
daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/SimpleAuditLoggerBaseTest.java

https://jira.talendforge.org/browse/TPSVC-15325
clean up MDC properties after sending log 

TPSVC-15325: clean MDC context

---

daikon-spring/daikon-content-service/content-service-common/src/test/java/org/talend/daikon/content/DeletableResourceLoaderTest.java
daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/LocationUtils.java
daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ResourceResolver.java
daikon-spring/daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/S3ContentServiceConfigurationTest.java
daikon-spring/daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/S3DeletablePathResolverTest.java
pom.xml

* Fix incorrect class when using getResources(locationPattern)

fix(content-service) Fix content service getResource

---

README.md
daikon-multitenant/multitenant-spring-web/src/test/java/org/talend/daikon/multitenant/web/MultiTenantApplicationTest.java
daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ContentServiceConfiguration.java
daikon-spring/daikon-spring-examples/pom.xml
daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/CachedMongoClientProvider.java
daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/MongoClientProvider.java
daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/MultiTenancyMongoDbConfiguration.java
daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/MultiTenancyMongoDbFactory.java
daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/SimpleMongoClientProvider.java
daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/SynchronizedMongoClientProvider.java
daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/TenantInformationProvider.java
daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/AbstractMultiTenantMongoDbTest.java
daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/CachedMongoClientProviderTest.java
daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/DisabledMultiTenantMongoDbTest.java
daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/MultiTenantMongoDbFactoryTest.java
daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/SynchronizedMongoClientProviderTest.java
daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/TestMultiTenantConfiguration.java
daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Abstract.java
pom.xml

New service base images support Spring Boot 2.3.5. There are some change in Daikon that needs to be done to follow 2.3.x changes.
* Upgrade to Spring Boot 2.3.5
* Follow API changes.

feat(update) Upgrade to Spring Boot 2.3.5

---

README.md
daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ContentServiceConfiguration.java
daikon-spring/daikon-spring-examples/pom.xml
pom.xml

Follow release train
* Upgrade to Spring Boot 2.3.6
* Upgrade to Spring Cloud Hoxton.SR9
* Upgrade to Jackson 2.11.3

chore(upgrade) Move to Spring Boot 2.3.6 

---

daikon-signature-verifier/pom.xml
daikon-signature-verifier/src/main/java/org/talend/daikon/signature/verify/ZipVerifier.java
daikon-signature-verifier/src/test/java/org/talend/daikon/signature/verify/CertificateGenerater.java
daikon-signature-verifier/src/test/java/org/talend/daikon/signature/verify/SignedFileGenerater.java
daikon-signature-verifier/src/test/java/org/talend/daikon/signature/verify/ZipUtil.java
daikon-signature-verifier/src/test/java/org/talend/daikon/signature/verify/ZipVerifierWithExpiredCertTest.java
daikon-signature-verifier/src/test/resources/log4j.xml

https://jira.talendforge.org/browse/TDKN-302

TDKN-302 Update daikon for job certification issues

---

daikon-tql/daikon-tql-client/package.json
daikon-tql/daikon-tql-core/src/main/resources/tql/package.json

package.json versions were not matching the published packages

chore(tql-js-client): bump versions

---

daikon-spring/daikon-spring-examples/pom.xml
pom.xml

chore(cve) Fix for CVEs

---

daikon-crypto/crypto-utils/pom.xml
daikon-exception/pom.xml
daikon/pom.xml
pom.xml

Backport CVE fixes to 0.31 maintenance branch.

Backport CVE fixes to 0.31 maintenance branch.

---

daikon-crypto/crypto-utils/pom.xml
daikon-exception/pom.xml
daikon/pom.xml
pom.xml

Backport from security fixes from 2.0

Backport from security fixes from 2.0

---

daikon-crypto/crypto-utils/pom.xml
daikon-exception/pom.xml
daikon/pom.xml
pom.xml

Here we are backporting some CVE fixes from 2.1

Here we are backporting some CVE fixes from 2.1

---

daikon-crypto/crypto-utils/pom.xml
daikon-exception/pom.xml
daikon/pom.xml
pom.xml

Here we are backporting some CVE fixes from 3.1

Backport security fixes from 3.1

---

daikon-spring/daikon-spring-reactive/daikon-spring-reactive-security/README.md
daikon-spring/daikon-spring-reactive/daikon-spring-reactive-security/pom.xml
daikon-spring/daikon-spring-reactive/daikon-spring-reactive-security/src/main/java/org/talend/daikon/security/tenant/JwtTenancyContextWebFilter.java
daikon-spring/daikon-spring-reactive/daikon-spring-reactive-security/src/main/java/org/talend/daikon/security/tenant/ReactiveTenancyContextHolder.java
daikon-spring/daikon-spring-reactive/daikon-spring-reactive-security/src/main/java/org/talend/daikon/security/tenant/TenancyContextWebFilter.java
daikon-spring/daikon-spring-reactive/daikon-spring-reactive-security/src/test/java/org/talend/daikon/security/tenant/JwtTenancyContextWebFilterTest.java

chore(): add ReactiveTenancyContextHolder inside reactive chain of call

---

daikon-logging/logging-event-layout/README.adoc
daikon-logging/logging-event-layout/pom.xml
daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/ecs/EcsFieldsChecker.java
daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/ecs/EcsSerializer.java
daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/Log4j2JSONLayout.java
daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/LogbackJSONLayout.java
daikon-logging/logging-event-layout/src/main/resources/custom_flat.yml
daikon-logging/logging-event-layout/src/main/resources/ecs_flat.ftl
daikon-logging/logging-event-layout/src/main/resources/logging.properties
daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/ecs/CustomFieldsTest.java
daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/ecs/EcsFieldCheckerTest.java
daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/AbstractLayoutTest.java
pom.xml

https://jira.talendforge.org/browse/TPSVC-17155

[TPSVC-17155] Added support for custom ECS fields

---

daikon-spring/daikon-spring-reactive/daikon-spring-reactive-multitenant-mongo/pom.xml
daikon-spring/daikon-spring-reactive/daikon-spring-reactive-multitenant-mongo/src/main/java/org/talend/daikon/mongo/CachedMongoClientProvider.java
daikon-spring/daikon-spring-reactive/daikon-spring-reactive-multitenant-mongo/src/main/java/org/talend/daikon/mongo/ReactiveMongoClientProvider.java
daikon-spring/daikon-spring-reactive/daikon-spring-reactive-multitenant-mongo/src/main/java/org/talend/daikon/mongo/ReactiveTenantInformationProvider.java
daikon-spring/daikon-spring-reactive/daikon-spring-reactive-multitenant-mongo/src/main/java/org/talend/daikon/mongo/TenancyReactiveMongoTemplate.java
daikon-spring/daikon-spring-reactive/daikon-spring-reactive-multitenant-mongo/src/main/java/org/talend/daikon/mongo/TenantInformation.java
daikon-spring/daikon-spring-reactive/daikon-spring-reactive-multitenant-mongo/src/test/java/org/talend/daikon/mongo/CachedMongoClientProviderTest.java
daikon-spring/daikon-spring-reactive/pom.xml

chore(): add TenancyReactiveMongoTemplate mecanism

---

daikon-spring/daikon-spring-reactive/daikon-spring-reactive-security/src/main/java/org/talend/daikon/security/filter/AuthorizationExchangeFilterFunction.java

fix potentiel NPE on AuthorizationExchangeFilterFunction

chore(): fix potentiel NPE on AuthorizationExchangeFilterFunction

---

README.md
daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/ecs/EcsSerializer.java
daikon-spring/daikon-spring-examples/pom.xml
pom.xml

Need Daikon release aligned with Talend-standardized BOMs.
* Upgrade Spring Boot (2.3.8 -> 2.3.9).
* Update readme to prepare release.

chore(upgrades) Upgrade to Spring Boot 2.3.9

---

README.md
daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/ecs/EcsSerializer.java
daikon-spring/daikon-spring-examples/pom.xml
pom.xml

Follow Talend-standardized library release train.
* Upgrade Spring Boot (2.3.9 -> 2.3.10)
* Upgrade Spring Cloud (Hoxton SR10 -> Hoxton SR11)
* Documentation update.

chore(upgrades) Upgrade to Spring Boot 2.3.10

---

daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditLogAutoConfiguration.java

This PR is complementary to #737. The goal is to add a tag to the counter in order to allow proper filtering in thanos 
https://jira.talendforge.org/browse/TPSVC-13666

feat(TPSVC-13666): add tag to the prometheus audit log counter

---

daikon-statistic/src/main/java/org/talend/daikon/statistic/pojo/HistogramStatistic.java
daikon-statistic/src/main/java/org/talend/daikon/statistic/pojo/HistogramUnit.java
daikon-statistic/src/main/java/org/talend/daikon/statistic/pojo/KeyValueStatistic.java
daikon-statistic/src/main/java/org/talend/daikon/statistic/pojo/SimpleStatistic.java
daikon-statistic/src/main/java/org/talend/daikon/statistic/pojo/Statistic.java

chore(): Set statistics Serializable

---

README.md
daikon-spring/daikon-spring-examples/pom.xml
pom.xml

chores(upgrades) Upgrade to Spring Boot 2.3.11

---

daikon-messages/messages-model/pom.xml

Unify the Daikon messages Kafka version with the root pom.

TDKN-314 - Unify Kafka client versions

---

Jenkinsfile

TSBI image for building librairies is outdated (no immediate problem though).
* Update builder image to a newer version.
* Misc: remove unused variable in script.
No Jira

chore(build): Update TSBI builder to newer version.

---

daikon-schema/daikon-dataset-sample/src/test/java/org/talend/daikon/sample/SampleMetadataSchemaValidatorTest.java

chore(TPGOV-2071): fix format
