- daikon/src/main/java/org/talend/daikon/number/BigDecimalParser.java
* Add missing 'final' keyword for constant DecimalFormat fields.
* Adds synchronized on DecimalFormat instance before using it for parsing big decimal.
> Fix concurrent access to DecimalFormat fields in BigDecimalParser

- daikon/src/main/java/org/talend/daikon/avro/SchemaEDIConstants.java
- daikon/src/main/java/org/talend/daikon/avro/SchemaExternalConstants.java
This is the first attempt at sharing some avro schema custom properties needed for TDM.  In the long term, TDM will require more custom properties than these but this should get us started for 6.3.0.
Rather than modifying the SchemaConstants class, I have created 2 new classes. It seems cleaner to have smaller, specialized, classes rather than a massive multipurpose one.
> TDM-5337 Share TDM avro schema custom properties in DAIKON

- daikon/src/main/java/org/talend/daikon/properties/presentation/Form.java
- daikon/src/test/java/org/talend/daikon/properties/presentation/FormTest.java
This pull request will help the readability of the "refreshLayout" part of a componentProperty.
It will change the code from:
```
if (useOtherConnection) {
form.getWidget(useDataSource.getName()).setHidden(true);
form.getWidget(dataSource.getName()).setHidden(true);
} else {
form.getWidget(useDataSource.getName()).setHidden(false);
form.getWidget(dataSource.getName()).setHidden(!useDataSource.getValue());
}
```
to:
```
if (useOtherConnection) {
form.getWidget(useDataSource).setHidden(true);
form.getWidget(dataSource).setHidden(true);
} else {
form.getWidget(useDataSource).setHidden(false);
form.getWidget(dataSource).setHidden(!useDataSource.getValue());
}
```
> TCOMP-313: Add a the possibility for the Form to retrieve a Widget directly  from a Property.

- daikon/src/main/java/org/talend/daikon/di/DiIncomingSchemaEnforcer.java
- daikon/src/test/java/org/talend/daikon/di/DiIncomingSchemaEnforcerTest.java
1. When DiIncomingSchemaEnforcer.initDynamicColumn(...) take all of the parameters from the dynamic metadata and adapt it to a field for the runtime Schema. The mapping miss some type like:
id_Byte/id_Short/id_BigDecimal/id_Date/id_Character
2. When pass unsupported type, the field schema would put null.This would caused NPE problem
Add above missing and throw a UnsupportedOperationException for unsupported type
> fix (TDI-37525): add missing type mapping when DiIncomingSchemaEnforcer initialize dynamic column

- daikon/src/main/java/org/talend/daikon/di/DiOutgoingSchemaEnforcer.java
- daikon/src/test/java/org/talend/daikon/di/DiOutgoingSchemaEnforcerTest.java
Because of BigDecimal and Character type save String type value in avro.
But in the DiOutgoingSchemaEnforcer  transform from Avro-compatible to  Talend-compatible types
We miss those 2 type convert.
Add above missing
> fix (TDI-37525): add missing when DiOutgoingSchemaEnforcer transform from Avro-compatible to  Talend-compatible types

- daikon/src/main/java/org/talend/daikon/properties/presentation/Form.java
- daikon/src/main/java/org/talend/daikon/properties/presentation/Widget.java
- daikon/src/test/java/org/talend/daikon/properties/PropertiesTest.java
- daikon/src/test/java/org/talend/daikon/properties/PropertyTest.java
- daikon/src/test/java/org/talend/daikon/properties/presentation/FormTest.java
Add a couple of method into widget to improve the usability of the "refreshLayout" method.
The list of the added method is:
```
public Widget setHidden(Property<Boolean> hidden)
public Widget setHidden()
public Widget setVisible(boolean visible)
public Widget setVisible(Property<Boolean> visible)
public Widget setVisible()
```
It will change the code from:
```
if (useOtherConnection) {
form.getWidget(useDataSource).setHidden(true);
form.getWidget(dataSource).setHidden(true);
} else {
form.getWidget(useDataSource).setHidden(false);
form.getWidget(dataSource).setHidden(!useDataSource.getValue());
}
```
into:
```
if (useOtherConnection) {
form.getWidget(useDataSource).setHidden();
form.getWidget(dataSource).setHidden();
} else {
form.getWidget(useDataSource).setVisible(); …
```
> TCOMP-313: Add "setVisible" method on Widget.

- daikon-service/service-common/src/test/java/org/talend/daikon/RandomServerPortFinder.java
- daikon-service/service-common/src/test/resources/application.properties
**What is the current behavior?**
https://jira.talendforge.org/browse/TDKN-86 Unit tests in service-common module run on a static port, making them unstable in case of concurrent builds on same machine.
Unit tests now use a random port (based on Spring's random port finder).
* Unit test now run on random HTTP port.
* Add configuration to dynamically build the available server list using the random port number.
> TDKN-86: Fix use of static HTTP port in configuration.

- daikon/pom.xml
- daikon/src/main/java/org/talend/daikon/di/DiOutgoingSchemaEnforcer.java
- daikon/src/test/java/org/talend/daikon/di/DiOutgoingSchemaEnforcerTest.java
daikon bundle expects joda-time package to be provided by another bundle. this break *components* build.
I have embedded joda-time in the bundle. I did not exported it cause it is used by DI specific classes that are supposed to be moved to the Studio. 
I have made the maven dependencies optional to not impact other projects relying on daikon because all of them will never use the di classes.
> fix (TDI-37709) : remove jodatime in daikon bundle to fix comp build

- daikon/src/main/java/org/talend/daikon/avro/converter/CachedIndexedRecordConverterBase.java
- daikon/src/main/java/org/talend/daikon/avro/converter/ComparableIndexedRecordBase.java
- daikon/src/main/java/org/talend/daikon/avro/converter/SingleColumnIndexedRecordConverter.java
Currently, some IndexedRecord wrappers (adapting a technology-specific object) don't need to implement `compareTo` and can use the default behaviour for `equals()` and `hashCode()`
In a big data environment, however, it is important that two IndexedRecords that have identical content according to Avro correctly implement `equals()` and `hashCode()`.
Since Avro provides a standard mechanism to do this, this PR adds a base class to automatically provide coherent `equals()`, `hashCode()` and `compareTo()` methods.
If this PR contains a …
> Add a base class for IndexedRecord implementations that are Comparable.

- daikon/src/main/java/org/talend/daikon/definition/I18nDefinition.java
- daikon/src/main/java/org/talend/daikon/properties/PropertiesImpl.java
- daikon/src/test/java/org/talend/daikon/properties/TestAbstractPropertiesTest.java
- daikon/src/test/java/org/talend/daikon/properties/TestPropertiesTestUtils.java
- daikon/src/test/java/org/talend/daikon/properties/test/AbstractPropertiesTest.java
- daikon/src/test/java/org/talend/daikon/properties/test/PropertiesTestUtils.java
No test helper class exists to check on i18n and images for all definition kind. Only the one for the Components exists in the repo *components*
Add an Class *AbstractPropertiesTest* that can be extended to check that all i18n is properly setup.
A new *I18nDefinition* class is proposed to setup standard keys for i18n if the definitions.
see the related PR in *components* ( https://github.com/Talend/components/pull/339 )
> feat (test) : add a test base class for defintions and properties i18n

- daikon/src/main/java/org/talend/daikon/serialize/jsonschema/JsonPropertiesResolver.java
When parsing dataset properties with an empty Schema (e.g. JDBC dataset schema in dataprep), there a NullPointerException is triggered.
No exception is thrown.
> bug: prevent NullPointerException when parsing an empty Schema 

- daikon/src/main/java/org/talend/daikon/di/DiOutgoingSchemaEnforcer.java
- daikon/src/test/java/org/talend/daikon/di/DiOutgoingSchemaEnforcerTest.java
tsalesforceOutput type convert issue for BigDecimal when it has outconnector in 622
This bug has been fixed in 6.3.1 so I just do the backport.
> TDI-37740:tsalesforceOutput type convert issue for BigDecimal 

- daikon/src/main/java/org/talend/daikon/runtime/RuntimeUtil.java
If the maven.local.repo is set, it will override the org.ops4j.pax.url.mvn.localRepository.
This change is mainly necessary during builds and tests, but it is also logical that if a user has set the maven.local.repo system property to use it during pax resolution of mvn URLs.
> fix: When setting up mvn URL handlers, use maven.repo.local

- daikon/pom.xml
- daikon/src/main/java/org/talend/daikon/runtime/RuntimeUtil.java
- daikon/src/main/java/org/talend/daikon/sandbox/SandboxedInstance.java
- daikon/src/test/java/org/talend/daikon/sandbox/SandboxInstanceFactoryTest.java
- daikon/src/test/java/org/talend/daikon/sandbox/SandboxedInstanceTest.java
when a sandboxed classloader in created by 2 threads and using the same jars, and one is closed before the second tries to load some classes, an IllegalStateException occurs.
The JVM caching for URL connection has been removed to avoid this behavior.
I have also cleaned the way the sandboxed is closed (not related to this PR but necessary)
> fix(TCOMP-395): removed JVM caching for mvn URL connections

- daikon/src/main/java/org/talend/daikon/runtime/RuntimeInfo.java
- daikon/src/main/java/org/talend/daikon/runtime/RuntimeUtil.java
- daikon/src/main/java/org/talend/daikon/sandbox/SandboxInstanceFactory.java
- daikon/src/main/java/org/talend/daikon/sandbox/SandboxedInstance.java
- daikon/src/main/java/org/talend/java/util/ClosableLRUMap.java
- daikon/src/test/java/org/talend/daikon/sandbox/SandboxInstanceFactoryTest.java
- daikon/src/test/java/org/talend/daikon/sandbox/SandboxedInstanceTest.java
- daikon/src/test/java/org/talend/daikon/sandbox/properties/ClassLoaderIsolatedSystemPropertiesStaticInitTest.java
- daikon/src/test/java/org/talend/java/util/ClosableLRUMapTest.java
Caching this the SandboxedClassLoader allow us to gain computation time on the
classloading after its first intanTiation.
Adding a ClosableLRUMap algorithm to clear automatically the cache if there
is too many ClassLoader instanciated at the same time.
Currently, a SandboxedClassLoader is created for each time there is a rest call. This create a delay of 1 seconds during the class loading and 2 second for the instantiation of a beam pipeline.
Reusing existing SandboxedClassLoader allow us to highly improve this computation time (aka: reduce it to 0 second)
**Does this PR introduce a …
> feat(fileIO): cache SandboxedClassLoader.

- daikon/pom.xml
- daikon/src/main/java/org/talend/daikon/runtime/RuntimeUtil.java
- daikon/src/test/java/org/talend/daikon/sandbox/SandboxInstanceFactoryTest.java
- daikon/src/test/resources/log4j.properties
see TCOMP-402, when resolving jar classpath, the pax mvn resolver failed on wrong URLs
those URL with versions ending with *.jar* are considered wrong URL.
> fixed(TCOMP-402):fixed wrong artifact resolution with UrlClassLoader

- daikon/src/main/java/org/talend/daikon/avro/converter/WrappedList.java
- daikon/src/test/java/org/talend/daikon/avro/converter/WrappedListTest.java
Throw NPE when check the size of the WrappedList, if the actual list in the WrappedList is null
use Empty list instead of Null
> fix(WrappedList): fix npe when the actual list is null

- daikon/src/test/java/org/talend/daikon/properties/test/AbstractPropertiesTest.java
The assertComponentIsRegistered just tests the name of the component.
Deprecated the old assertComponentIsRegistered with a method that checks the requestClass and expected definition Class
The deprecated method should be removed before 1.0!
> Add helper method to assertComponentIsRegistered.

- daikon/src/main/java/org/talend/daikon/definition/Definition.java
- daikon/src/main/java/org/talend/daikon/definition/DefinitionImageType.java
- daikon/src/main/java/org/talend/daikon/exception/TalendRuntimeException.java
- daikon/src/main/java/org/talend/daikon/runtime/RuntimeInfo.java
- daikon/src/test/java/org/talend/daikon/properties/TestPropertiesTestUtils.java
- daikon/src/test/java/org/talend/daikon/properties/test/AbstractPropertiesTest.java
- daikon/src/test/java/org/talend/daikon/properties/test/PropertiesTestUtils.java
The Definition class only offers a mechanism to get the image path (probably an icon).
The Definition class only offers a mechanism to get the image path for different resource types, as well as an icon key.
**If this PR contains a breaking change, please describe the impact and migration path for existing applications**: ...
All existing definitions need to add the new methods for image resource discovery.  
This can be done for all components in a backwards compatible manner in AbstractComponentDefinition, which needs to be prepared for …
> feat(TCOMP-481): Clean up image path API for definitions.

- daikon/src/main/java/org/talend/daikon/serialize/SerializerDeserializer.java
- daikon/src/test/java/org/talend/daikon/serialize/jsonio/PersistenceObjectForFieldRemoved.java
- daikon/src/test/java/org/talend/daikon/serialize/jsonio/SerializeDeserializeTest.java
- pom.xml
when deserializing a field that is missing that was serialized with enough type information, the handler was notified with a null  value
Now if the object can be deserialized, the handle gets the proper value. This is useful for field that where renamed.
This PR will require some Studio update for the new json-io version. So please merge this branch https://github.com/Talend/studio-se-master/tree/bugfix/json-io_migration_with_complex_types once this PR is merged.
> fix(migration):use latest json-io to improve missing field during migration

- daikon-spring/daikon-spring-mongo/pom.xml
build failed for *spring-mongo* module on a new machine cause the maven plugin could not be dowloaded
added the right maven plugin repo to download the missing plugin
> chore(spring-mongo):add plugin repo for maven plugin resolution

- .gitattributes
the configuration in the .gitattributes file is not taking effect on java files. this doesn't work on windows machine. and the build fails with a :
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:1.6.0-SNAPSHOT:validate (default) on project daikon: File '...\daikon\src\main\java\org\talend\daikon\avro\AvroRegistry.java' format doesn't match!
we added the *.java to the file to force line ending format on all environment and with no need for a local git configuration. 
If this PR contains a breaking change, …
> style: end-of-line normaliaztion to lf for *.java files

- daikon-content-service/content-service-common/src/test/java/org/talend/daikon/content/DeletableResourceTest.java
- daikon-content-service/s3-content-service/README.md
- daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/IncorrectS3ConfigurationAnalyzer.java
- daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/LocationUtils.java
- daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ContentServiceConfiguration.java
- daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ResourceResolver.java
- daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/provider/AmazonS3Provider.java
- daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/provider/S3BucketProvider.java
- daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/S3DeletableResourceTest.java
- daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/TestConfiguration.java
- daikon-content-service/s3-content-service/src/test/resources/META-INF/spring.factories
- daikon-content-service/s3-content-service/src/test/resources/application.properties
**What is the current behavior?** 
Impossible to change S3 bucket name at runtime.
Add multi tenancy support to S3 (allow to change bucket name at runtime).
* Add "multi-tenancy.s3.active" to activate multi tenant in S3 resource resolver.
* Improve error message in case of misconfiguration relative to S3 configuration.
* Update README with multi tenant usage.
> [feature] Multi tenancy support for S3

- daikon/src/main/java/org/talend/daikon/serialize/jsonschema/UiSchemaGenerator.java
- daikon/src/test/java/org/talend/daikon/serialize/jsonschema/UiSchemaGeneratorTest.java
- daikon/src/test/resources/org/talend/daikon/serialize/jsonschema/ReferenceExampleUiSchema.json
When you hide ALL of the elements inside nested properties (i.e. no form components are expected to be shown), the `Properties` will still show its title.  As a consequence, you have a title in the UI without any form components to adjust.
This is particularly confusing for `SchemaProperties` when the Schema itself is hidden.  We see a MAIN schema title without any editor.
When you hide ALL of the elements inside nested properties, the `ui:widget` for the Properties is also set to `hidden`.
> fix(TFD-1000): Hide nested properties with no visible widgets.

- daikon-content-service/content-service-common/src/test/java/org/talend/daikon/content/DeletableResourceTest.java
- daikon-content-service/local-content-service/src/test/java/org/talend/daikon/content/local/LocalDeletableResourceTest.java
- daikon-content-service/s3-content-service/README.md
- daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/LocationUtils.java
- daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ContentServiceConfiguration.java
- daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3DeletableResource.java
- daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ResourceResolver.java
- daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/provider/S3BucketProvider.java
- daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/AmazonS3TestWrapper.java
- daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/S3DeletableResourceTest.java
- daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/TestConfiguration.java
There was no way to configure the root directory per tenant in the S3 content service. This is required by TDP-3377.
Similarly to multi tenancy in MongoDB, S3BucketProvider can provide the root directory.
> feat(TDP-3377): Allow S3 Bucket provider to customize root directory

- daikon/src/main/java/org/talend/daikon/properties/PropertiesImpl.java
- daikon/src/main/java/org/talend/daikon/properties/ReferenceProperties.java
- daikon/src/test/java/org/talend/daikon/properties/ReferencePropertiesTest.java
- ReferenceProperties doesn't traverse referenced properties instance when accepting a visitor and as, consequence, referenced properties are excluded from processing (f.x. encryption of properties before serialization to JSON)
- ReferenceProperties traverse referenced properties instance when accepting a visitor, referenced properties are included into processing (f.x. encryption of properties before serialization to JSON) …
> fix(TCOMP-538): Fix visiting of referenced properties in ReferenceProperties

- daikon-logging/.gitignore
- daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/Log4jJSONLayout.java
- daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/LogbackJSONLayout.java
LogLog.debug is used in Layout classes which causes an error, when Logback layout is used.
When Logback is used log4j classes are not present in classpath, thus NoClassDefFoundException appears
LogLog.debug was removed
Related to https://jira.talendforge.org/browse/TCOMP-541
> fix(TCOMP-541): remove LogLog.debug from layout classes

- daikon-logging/logging-event-layout/README.MD
Current example logging configuration for logback has an error: param name="UserFields" value="" - value is empty. If you use such configuration than logs are not written. 
Fixed an error in logback and other configuration examples
Related to https://jira.talendforge.org/browse/TCOMP-541
> fix(TCOMP-541): fix logging configuration examples

- daikon/src/main/java/org/talend/daikon/properties/Properties.java
- daikon/src/main/java/org/talend/daikon/properties/PropertiesDynamicMethodHelper.java
- daikon/src/main/java/org/talend/daikon/properties/PropertiesImpl.java
- daikon/src/main/java/org/talend/daikon/properties/ReferenceProperties.java
- daikon/src/test/java/org/talend/daikon/properties/ReferenceExampleProperties.java
- daikon/src/test/java/org/talend/daikon/properties/ReferencePropertiesTest.java
- daikon/src/test/resources/org/talend/daikon/serialize/jsonschema/ReferenceExampleUiSchema.json
refreshProperties where hastily developed for dataprep cause there was a need to update the current properties state after the Properties is deserialized and references are setup. This is not required.
Properties already has a deserialized method to be overriden if necessary but for notification after the references are setup the Studio already use an after callback, so I also implemented it when the references are automatically resolved in daikon. 
If this PR contains a breaking change, please describe the impact and migration path for …
> feat(TDKN-167):remove refreshProperties and added ref after callback

- daikon/src/main/java/org/talend/daikon/sandbox/SandboxControl.java
- daikon/src/main/java/org/talend/daikon/sandbox/SandboxInstanceFactory.java
- daikon/src/test/java/org/talend/daikon/sandbox/SandboxInstanceFactoryTest.java
The SandboxInstanceFactory reuses ClassLoaders from a cache to improve performance.
Normally this is not a problem, since ClassLoaders are *mostly* stateless.   The exception is static variables inside loaded classes, which can retain state across runtime instances.
The SandboxControl class is an optional interface that the RuntimeInfo can implement to determine whether the ClassLoader should be reused by the SandboxedInstanceFactory.
Most runtime instances should continue with the current behaviour, but HDFS has static state that causes problems after a certain length of time and …
> fix(TCOMP-422): Add finer-grained control to sandbox caching.

- daikon/src/main/java/org/talend/daikon/runtime/RuntimeUtil.java
- daikon/src/test/java/org/talend/daikon/runtime/RuntimeUtilTest.java
- daikon/src/test/java/org/talend/daikon/sandbox/SandboxInstanceFactoryTest.java
java tries to play around with mvn url when it tries to look for some files in the classloader. it basically creates new url from the base mvn uri, removes the last element of the uri (usually a version of a type) and replace it by  a file path which is completl nonsense for the mvn: protocol
mvn url that are created from an existing url and a path (spec) are simply ignoring the specs.
> fix(TCOMP-402):ignore mvn url created from an exisiting url

- daikon/src/main/java/org/talend/daikon/serialize/jsonschema/JsonSchemaGenerator.java
- daikon/src/test/java/org/talend/daikon/serialize/jsonschema/JsonSchemaGeneratorTest.java
NPE when serializing ui-specs of a 2 nested properties that are not added to a form.
fixed the NPE.
> fix(TDKN-175):fix NPE when double nested unused props in uispecs

- daikon-logging/logging-event-layout/README.MD
cloud logs do not have enough information to identify them
The readme for logging was updated to add the *service* and *application* custom fields and make them compulsory.
https://jira.talendforge.org/browse/TDKN-178
> doc(TDKN-178):added service and application custom field

- daikon-tql/daikon-tql-mongo/src/main/java/org/talend/tqlmongo/ASTVisitor.java
A protected getter is needed for isNegation attribute in ASTVisitor, it has been turned to private (thank you codacy -_-), as well as the method patternToMongoRegex().
Add a protected getter for isNegation, and make patternToMongoRegex protected.
https://jira.talendforge.org/browse/TDS-1288
> TDS-1288 : Add getter for isNegation.

- daikon/src/main/java/org/talend/daikon/serialize/jsonschema/WidgetSpecificJsonSchemaUtils.java
- daikon/src/test/java/org/talend/daikon/serialize/jsonschema/JsonSchemaGeneratorTest.java
When a widget contains a list property, minItems is automatically set to 1, causing UI validation issues when widget is hidden in form.
To prevent validation issues, set to minItems=0 if widget for property is hidden.
https://jira.talendforge.org/browse/TDKN-179
> fix(TDKN-179): Set to minItems=0 for hidden list fields

- daikon/src/main/java/org/talend/daikon/converter/LocalDateConverter.java
- daikon/src/main/java/org/talend/daikon/converter/TypeConverter.java
- daikon/src/test/java/org/talend/daikon/converter/LocalDateConverterTest.java
- daikon/src/test/java/org/talend/daikon/converter/TypeConverterTest.java
The existing localDateTimeConverter does not handle dates with no time part
Add a LocalDateConverter to handle dates with no time part
> feat(TFD-1696) : Add a LocalDateConverter

- daikon-logging/logging-event-layout/README.MD
- daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/Log4jJSONLayout.java
- daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/LogbackJSONLayout.java
- daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/Log4jJSONLayoutTest.java
- daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/LogBackJSONLayoutTest.java
Log4J and logback locationInfo was set to true.
We set it to false by default (as is the case
for built-in log layouts).
> chore(logging): set locationInfo to false

- daikon-tql/daikon-tql-client/README.md
- daikon-tql/daikon-tql-client/src/converter/__tests__/compositor.spec.js
- daikon-tql/daikon-tql-client/src/converter/__tests__/modifier.spec.js
- daikon-tql/daikon-tql-client/src/converter/__tests__/parser.spec.js
- daikon-tql/daikon-tql-client/src/converter/__tests__/query.spec.js
- daikon-tql/daikon-tql-client/src/converter/compositor.js
- daikon-tql/daikon-tql-client/src/converter/modifier.js
- daikon-tql/daikon-tql-client/src/converter/query.js
There is no `not` modifier in the TQL client proposal.
Add a new `Modifier` class which can be part of a query. It accepts a type (`not`) and a `Quey` or `Operator`.
```javascript
const q1 = new Query();
const q2 = new Query();
q2
.equal('q2f1', 76)
.or()
.greaterThan('q2f2', 666);
q1
.greaterThan('f2', 42)
.or()
.not(q2);
```
Will give the following result :
```
(f2 > 42) or not((q2f1 = 76) or (q2f2 > 666))
```
> feat(daikon-tql-client): add modifiers

- daikon-multitenant/multitenant-spring-async/src/main/java/org/talend/daikon/multitenant/async/AsyncSupportAutoConfiguration.java
- daikon-multitenant/multitenant-spring-async/src/main/resources/META-INF/spring.factories
- daikon-multitenant/multitenant-spring-web/src/main/java/org/talend/daikon/multitenant/web/TenancyFiltersAutoConfiguration.java
- daikon-multitenant/multitenant-spring-web/src/main/resources/META-INF/spring.factories
Spring AutoConfiguration classes should
contain AutoConfiguration in their name
for easier differentiate them
from classic Configuration classes.
> chore(multi-tenancy): AutoConf classes name

- daikon/src/main/java/org/talend/daikon/converter/LocalDateConverter.java
- daikon/src/main/java/org/talend/daikon/converter/LocalDateTimeConverter.java
- daikon/src/main/java/org/talend/daikon/converter/LocalTimeConverter.java
- daikon/src/test/java/org/talend/daikon/converter/LocalDateConverterTest.java
- daikon/src/test/java/org/talend/daikon/converter/LocalDateTimeConverterTest.java
- daikon/src/test/java/org/talend/daikon/converter/LocalTimeConverterTest.java
We are currently using an UNEXPECTED_EXCEPTION when there is a problem parsing dates.   We can use a better type to give a more informative message on the UI.
Add an error code and specific TalendRuntimeException for DateTimeFormatter parsing errors.
https://jira.talendforge.org/browse/TFD-2824
> fix(TFD-2824): Use specific exceptions for date parsing.

- daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/SynchronizedMongoClientProvider.java
The CachedMongoClientProvider is not threadsafe, especially close method, leading to errors during application runtime (_state should be: open_ message).
To avoid this, TDP team implemented a SynchronizedMongoClientProvider, which prevents such concurrency problems.
This PR aims at moving this SynchronizedMongoClientProvider from TDP to daikon to share it between all Talend apps.
> chore(MultiTenancy): move thread safe mongo client provider from tdp to daikon

- daikon-content-service/local-content-service/README.md
* Add missing `content-service.store.local.path` documentation.
> chore(readme): Add missing directory configuration

- daikon-audit/docs/README.adoc
- daikon-audit/src/main/java/org/talend/logging/audit/impl/AuditConfiguration.java
- daikon-audit/src/main/java/org/talend/logging/audit/impl/Log4j1Configurer.java
- daikon-audit/src/main/java/org/talend/logging/audit/impl/LogAppendersSet.java
- daikon-audit/src/main/resources/audit.properties.example
- daikon-audit/src/test/java/org/talend/logging/audit/impl/AuditConfigurationTest.java
- daikon-audit/src/test/java/org/talend/logging/audit/impl/UtilsTest.java
- daikon-audit/src/test/resources/test.audit.properties
This PR adds support for placeholders in audit configuration file. The placeholder is replaced with a value from either system properties, environment vars or a default.
Additionally, this PR introduces support for multiple appenders for audit logs. 
> [Audit] Support for placeholders in configuration file

- pom.xml
mvn release plugin requires pushChanges=true to be able to chain prepare and perform goals,
currently daikon was not supporting it
keep the same default but support to override it through the command line using a maven property
> ensure pushChanges is configurable

- daikon/src/main/java/org/talend/daikon/properties/PropertiesImpl.java
- daikon/src/test/java/org/talend/daikon/properties/PropertiesListTest.java
- daikon/src/test/java/org/talend/daikon/properties/TestPropertiesList.java
This reverts commit 2d20a812a5e24426f303c6ffccdb5d8b25d05db6.
oops I did push to master (and reverted it) but this commit unrevert it.
PropertiesList i18n is not handled properly
now it is
https://jira.talendforge.org/browse/TDKN-195
> fix(TDKN-195): fix i18n for ListProperties

- daikon/src/main/java/org/talend/daikon/avro/AvroNamesValidationHelper.java
- daikon/src/main/java/org/talend/daikon/avro/JavaNamesValidationHelper.java
- daikon/src/test/java/org/talend/daikon/avro/AvroNamesValidationHelperTest.java
* added utility methods for validation of field names
Utility methods are necessary to validate the field names on Java conventions.
Add utility methods to daikon, so that this functionality will be available in all components
https://jira.talendforge.org/browse/TMDM-11854
> fix(TMDM-11854): Output with keywords fields names

- daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/CachedMongoClientProvider.java
- daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/MongoClientProvider.java
- daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/SimpleMongoClientProvider.java
- daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/SynchronizedMongoClientProvider.java
- daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/AbstractMultiTenantMongoDbTest.java
- daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/CachedMongoClientProviderTest.java
- daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/MultiTenantMongoDbFactoryTest.java
- daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/SynchronizedMongoClientProviderTest.java
- daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/TestMultiTenantConfiguration.java
`MongoClient` comes from a cache managed by `CachedMongoClientProvider`. Current implementation in `org.talend.daikon.spring.mongo.SynchronizedMongoClientProvider` performs a direct close on the mongo client:
```java
delegate.get(tenantInformationProvider).close();
```
This leads to a major issue, in case of sequential access to the mongo client with operations such as:
```
SynchronizedMongoClientProvider provider = ...;
provider.get(tenant1);
provider.close(tenant1); // (1)
provider.get(tenant1); // (2) <- returned client may be closed
```
This only happens when (1) and (2) are performed in less time than the renewal of mongo clients (which is what `CachedMongoClientProvider` does).
Bottom line is: in case of many concurrent …
> fix(TDP-5356): Reuse of mongo clients may lead to closed clients.

- daikon-tql/daikon-tql-core/src/main/antlr4/TqlLexer.g4
- daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/parser/TqlExpressionVisitor.java
- daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/api/TestTqlApi_Comply.java
- daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/api/TestTqlApi_Contains.java
- daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/api/TestTqlApi_FieldComparison.java
- daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/api/TestTqlApi_Match.java
The TQL support filters like : field = 'literal value'. The apostrophe ' is used as a delimiter, to let ANTLR find literal tokens. But if the literal itself contains an apostrophe, the TQL is not able do parse correctly the literal: depending of the whole filter parsed by TQL, either it leads to an exception being thrown during the parse operation, either the literal value is truncated and then the TQL results are not consistent with the filter.
- The TQL grammar now accepts literal with single quotes inside, eg _O'Reilly_ is now accepted. (see TQLParser.g4)
- After the parse operation, the grammar rules which use a literal value unescape single quotes from the literal inputs. …
> feat(TDS-3154): support single quotes in TQL queries

- daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/parser/TqlExpressionVisitor.java
- daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/TestTqlParser_AllFields.java
There were a few cases missing for support of "*" (all fields wildcard). This PR fixes the following limitations:
* Fix support of "*" when using "in" clause.
* Fix support of "*" when using "~" (regex match) clause.
* Fix support of "*" when using "contains" clause.
Fix the issues without breaking everything else :).
Loosely related to implementation https://jira.talendforge.org/browse/TDP-4346.
> fix: Additional fixes for TQL

- daikon-messages/messages-demo/demo-listener/pom.xml
- daikon-messages/messages-demo/demo-producer/pom.xml
A docker image is build for demo projects which is not usefull at all and also fail on mac machine because of the spotify maven plugin 
Docker build was made optional using a -Pdocker maven option. (The build on mac will still fail).
> chore(release): made docker build for messages demo optional

- daikon-spring/daikon-spring-mongo/pom.xml
There was a hardcoded repository URL in `daikon-spring-mongo` that was pushing branch build to Talend's snapshot repository. This was causing build instability for apps that depends on `daikon-spring-mongo` because it could bring branch version into app build.
Use the property changed by CI (${talend_snapshots_deployment}) to select Nexus repository.
https://jira.talendforge.org/browse/DEVOPS-1729
> fix(DEVOPS-1729): Fix distribution management for daikon-spring-mongo

- daikon-messages/messages-model/src/main/avro/MessageHeader.avsc
- daikon-messages/messages-model/src/test/java/org/talend/daikon/messages/header/TestMessageHeaderExtractor.java
The field OperationTypes  was accidently merged on master. The goal of this PR is to remove it
> fix(): Delete OperationTypes from header

- daikon-messages/messages-model-spring-support/src/main/java/org/talend/daikon/messages/spring/consumer/ExecutionContextUpdaterConfiguration.java
- daikon-messages/messages-model-spring-support/src/main/java/org/talend/daikon/messages/spring/consumer/sleuth/SpringSleuthSettersConfiguration.java
The current Sleuth configuration use the correlation ID as traceId for the span but without re-use the current span name (which is a mandatory field)
Use the current span name value for the new span name
https://jira.talendforge.org/browse/TDP-5779
> fix(TDP-5779): Update Spring Sleuth configuration for Span creation

- daikon-spring/daikon-spring-zipkin/pom.xml
- daikon-spring/daikon-spring-zipkin/src/main/java/org/talend/daikon/zipkin/EnableZipkinKafkaSender.java
- daikon-spring/daikon-spring-zipkin/src/main/java/org/talend/daikon/zipkin/ZipkinKafkaProperties.java
- daikon-spring/daikon-spring-zipkin/src/main/java/org/talend/daikon/zipkin/ZipkinKafkaSenderConfiguration.java
* Don't use `spring.*` prefix for non spring configuration properties
* Zipkin is enabled by default so the configuration should match even if the `spring.zipkin.enabled` property is not set
* we can't enable/disable the configuration
* use `talend.*` prefix
* configuration match if the property is missing
* add a `@EnableZipkinKafkaSender`
> fix(TDP-4665): add talend prefix for properties names

- daikon-spring/daikon-spring-zipkin/src/main/java/org/talend/daikon/zipkin/ZipkinKafkaSenderConfiguration.java
Do not load the Zipkin Configuration if the property `spring.zipkin.enabled` is not set to `true`.
Same solution than TDS:
* https://github.com/Talend/data-stewardship/blob/2fe91b0dcf73fbec28e0dd8c5102a516ab6528e0/data-stewardship-backend/data-history-service/src/main/java/org/talend/datasteward/util/HistoryZipkinKafkaSenderConfiguration.java#L26
https://jira.talendforge.org/browse/4668
> fix(TDP-4668) daikon spring zipkin conditions

- daikon-spring/daikon-spring-zipkin/pom.xml
Incompatibility between Daikon Kafka client and TDS/TDP Kafka client
Downgrading kafka client from client in order to use the same everywhere
> chore(): downgrade kafka client version

- daikon-spring/daikon-spring-zipkin/pom.xml
daikon-spring-zipkin use a zipkin kafka reporter which is not provided by the client (like TDP)
the zipkin kafka reporter library should be included in the daikon-spring-zipkin module
https://jira.talendforge.org/browse/4665
> fix(TDP-4665): daikon-spring-zipkin should include zipkin-sender-kafka

- daikon/src/main/java/org/talend/daikon/number/BigDecimalParser.java
- daikon/src/test/java/org/talend/daikon/number/BigDecimalParserTest.java
We need to get the supported decimal formats in tdp, and also the method guessSeparators().
The solution is to return the list of constants from the class BigDecimalParser and to make guessSeparators() public. 
https://jira.talendforge.org/browse/TDP-5153
> feat(TDP-5153): add method getSupportedFormats

- daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegex.java
- daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java
Refine the way to do char-pattern regexes by factorizing them when we have consecutively the same character
> feat(TDQ-15793): Factorize charPattern regexes

- daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/BeanPredicateVisitor.java
Solve the divergence between different TQL *complies* implementations and delegate it to the TDQ-15748
Use CharPatternToRegex from TDQ instead of the erronous custom complies implementation.
https://jira.talendforge.org/browse/15748
> feat(TDQ-15748): use TDQ tool in bean predicate visitor

- daikon/src/main/java/org/talend/daikon/pattern/PatternRegexUtils.java
- daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegex.java
- daikon/src/main/java/org/talend/daikon/pattern/word/WordPatternToRegex.java
- daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java
Escape '/' for java script regex
> feat(TDS-2682): escape '/' for javascript.

- daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_WordComply.java
- daikon/src/main/java/org/talend/daikon/pattern/PatternRegexUtils.java
- daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegex.java
- daikon/src/main/java/org/talend/daikon/pattern/word/WordPattern.java
- daikon/src/main/java/org/talend/daikon/pattern/word/WordPatternToRegexConstants.java
- daikon/src/test/java/org/talend/daikon/pattern/word/WordPatternToRegexTest.java
Hiragana and Katakana are not recognized on Word Pattern 
> feat(TDQ-15966): adapt word pattern for japanese

- daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Comply.java
- daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_WordComply.java
- daikon/src/main/java/org/talend/daikon/pattern/character/CharPattern.java
- daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegexConstants.java
- daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java
some special japanese characters were not taken into account in char-patterns
> fix(TDQ-15964): handle special japanese characters in char-patterns

- pom.xml
In the pom.xml in daikon, we want just import the package daikon-scala/dynamic-log. When we want to use the library in dataset, there is a problem with the import of dynamic-log.
Import all the package daikon-scala and not just import the package dynamic-log
https://jira.talendforge.org/browse/TDC-1373
> Fix : Fix module daikon.scala in pom.xml in daikon

- daikon/src/main/java/org/talend/daikon/avro/inferrer/JsonSchemaInferrer.java
- daikon/src/test/java/org/talend/daikon/avro/inferrer/JsonSchemaInferrerTest.java
The method inferSchema inside JsonSchemaInferrer will alway create an avro Schema named "outer_record".
This may result in conflict between two different AVRO schema.
Add an Hash to the schema name. 
> fix(TDKN-209): Add a deterministic hash to the avro schema name.

- daikon-messages/messages-model/pom.xml
- daikon-messages/messages-model/src/main/java/org/talend/daikon/messages/utils/HeadersUtils.java
The current MessageHeader is intended to be included in the kafka's value as a separate field, and the current Kafka clients version doesn't support Kafka headers.
Bump Kafka clients version to 1.1.1 and add a helper method to generate Kafka message headers from Daikon message header.
The Kafka headers can be used to do filtering/routing before deserializing the whole message.
Tests and doc to follow up soon.
https://jira.talendforge.org/browse/TFD-6171
> feat(TFD-6171) : add kafka headers support

- pom.xml
The daikon root pom has a (duplicate) dependency on Jackson 2.9.5. We should update to the latest 2.9.8 as there are several security advisories in effect against 2.9.5. For example:
https://nvd.nist.gov/vuln/detail/CVE-2018-19360
https://cve.mitre.org/cgi-bin/cvename.cgi?name=2018-14721
> TDKN-214 - Update Jackson

- Jenkinsfile
https://github.com/Talend/daikon/pull/434 introduced a dependency that does not support Linux 32-bit
Update to 64-bit jenkinsxio/builder-maven
None
> Use 64-bit Maven builder image (reqd by content-service-journal-mongo)

- daikon-exception/pom.xml
the Exception module is not a bundle on the maintenance branch 0.31
cherrypicked master fix on the branch to change the pom to make a bundle
https://jira.talendforge.org/browse/TDKN-213
> WorkItem(TDKN-213):Daikon exception is not an OSGI plugin (#432)

- daikon-scala/dynamic-log/dynamic-log-web-play/pom.xml
play2-maven-plugin.version is not used by the plugin
Update pom.xml to use it
> Update version of play2-maven-plugin

- README.md
Dead link in the readme.
Change content-service link and remove daikon-service.
> fix Readme links

- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AuditConfigurationMapImpl.java
- daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AuditConfigurationMapImplTest.java
Backport of #466
Fix audit config appender name parsing
Fix start index for substring.
https://jira.talendforge.org/browse/TDKN-222
> fix(TDKN-222) : fix audit config appender name parsing (#466)

- daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/LayoutUtils.java
- daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/LogbackJSONLayout.java
- daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/AbstractLayoutTest.java
- daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/LayoutUtilsTest.java
- daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/LogBackJSONLayoutTest.java
Using MDC in play applications is not straighforward and even not safe (see the `Limitation of the default implementation of the MDC` section in http://yanns.github.io/posts/2/). The way we might use it would be very intrusive in the code, by wrapping our logging events with the `MDC.put` and `MDC.clean`. Not ideal.
In order to workaround that limitation, the play documentation advices to use the markers of the logging events, to enrich the log messages (https://www.playframework.com/documentation/2.6.x/ScalaLogging#Using-Markers-and-Marker-Contexts).
This PR comes with the ability to enrich the customInfo field, with additional fields that might arrive as part of the logging …
> feat: use markers to dynamically populate some custom info

- daikon-tql/daikon-tql-client/README.md
- daikon-tql/daikon-tql-client/src/converter/operators/__tests__/greater-than-or-equal.spec.js
- daikon-tql/daikon-tql-client/src/converter/operators/__tests__/greater-than.spec.js
- daikon-tql/daikon-tql-client/src/converter/operators/__tests__/in.spec.js
- daikon-tql/daikon-tql-client/src/converter/operators/__tests__/less-than-or-equal.spec.js
- daikon-tql/daikon-tql-client/src/converter/operators/__tests__/unequal.spec.js
- daikon-tql/daikon-tql-client/src/converter/operators/greater-than-or-equal.js
- daikon-tql/daikon-tql-client/src/converter/operators/in.js
- daikon-tql/daikon-tql-client/src/converter/operators/index.js
- daikon-tql/daikon-tql-client/src/converter/operators/less-than-or-equal.js
- daikon-tql/daikon-tql-client/src/converter/operators/operator.js
- daikon-tql/daikon-tql-client/src/converter/operators/unequal.js
`in`, `lessThanOrEqual`, `greaterThanOrEqual`, `unequal` operators not existing in the client lib.
Add the implementation for each of them.
https://jira.talendforge.org/browse/TDKN-229
> feat(TDKN-229): Add more tql client operators

- daikon/src/main/java/org/talend/daikon/security/CryptoHelper.java
Deprecate CrytoHelper class.
See added deprecation description to CrytoHelper class. 
https://jira.talendforge.org/browse/TDKN-206
> chore(TDKN-206): Deprecate CrytoHelper class.

- daikon-messages/README.md
Remove code references to both @EnableMessagesProducerAutoConfig and @EnableMessagesConsumerAutoConfig (both annotation were removed during migration to Spring Boot 2).
Remove references to classes in documentation.
https://jira.talendforge.org/browse/TDKN-232
> fix(TDKN-232): Remove references to deleted annotations

- daikon/src/main/java/org/talend/daikon/number/BigDecimalParser.java
- daikon/src/test/java/org/talend/daikon/number/BigDecimalParserTest.java
* add management of space separators
* fix space management of inferDecimalSeparator
* add TUs
* fix existing TUs
Have the same management of decimals between TDP and Daikon.
https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html
Add code to manage more use cases
https://jira.talendforge.org/browse/TDKN-233
> fix(TDKN-233): manage more use cases in BigDecimalParser

- daikon/src/main/java/org/talend/daikon/security/CryptoHelper.java
TDKN-237 Provide getDefault() method for class org.talend.daikon.security.CryptoHelper on branch maintenance/0.31
Add getDefault() method 
https://jira.talendforge.org/browse/TDKN-237
https://jira.talendforge.org/browse/TDKN-237
> TDKN-237 Provide getDefault() method for class org.talend.daikon.security.CryptoHelper on branch maintenance/0.31

- daikon-spring/daikon-spring-examples/daikon-spring-example-security/README.adoc
- daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/resources/application-public-prometheus.properties
- daikon-spring/daikon-spring-security/README.adoc
- daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java
See https://jira.talendforge.org/browse/TDKN-238 (description part)
See https://jira.talendforge.org/browse/TDKN-238 (proposal part)
Feature
* Add `talend.security.allowPublicPrometheusEndpoint` to allow unauthenticated access to Prometheus endpoint (dev mode only, see Jira description).
* Documentation update.
* Example update.
Misc
* (improvement) use `WebEndpointProperties` to propertly secure actuator endpoints in case service configuration changes endpoint base path.
https://jira.talendforge.org/browse/TDKN-238
> feat(TDKN-238): Allow unauthenticated access to Prometheus

- daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java
in `daikon-spring-security` the health endpoint becomes protected with a token.
That's unexpected and prevent proper health checks. This endpoint should be available without authentication.
https://jira.talendforge.org/browse/TDKN-238
> feat(TDKN-238): Allow public access to /health

- daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java
The spring security policies enforce the usage of a CSRF token which prevent simple POST action in the Actuator or in REST controller.
The CSRF has been disabled
> fix(TDKN-238): disabled csrf for spring security

- daikon-crypto/crypto-utils/README.md
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/CipherSources.java
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/EncodingUtils.java
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/KeySources.java
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/digest/DigestSource.java
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/digest/DigestSources.java
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/digest/Digester.java
- daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/digest/DigestSourcesTest.java
- daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/digest/DigesterTest.java
Provide a way to digest a value using a salt.
Digest a value using "(salt, delimiter, value) -> (salt + delimiter + sha256(value))" as result (instead of a single `value -> sha256(value)`).
https://jira.talendforge.org/browse/TDKN-239
> chore(TDKN-239): Add Digester to crypto-utils

- daikon-crypto/daikon-signature-verifier/pom.xml
Commons Lang + SLF4J-log4j are listed as compile time dependencies, even though they are not used in src/main
> Remove unused dependencies from compile scope

- daikon-logging/logging-event-layout/README.MD
- daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/Log4j2JSONLayout.java
- daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/Log4jJSONLayout.java
- daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/LogbackJSONLayout.java
- daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/Log4j2JSONLayoutTest.java
- daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/Log4jJSONLayoutTest.java
See https://jira.talendforge.org/browse/TDKN-245
* Add ability to hide host information in appenders
* Standard clean up following default Intellij suggestions
https://jira.talendforge.org/browse/TDKN-245
> feat(TDKN-245): Add ability to hide host information in appenders

- daikon-spring/daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalResourceResolver.java
In TDP we need to wrap LocalResourceResolver. In order to do that we need that class to be public
Make the class public
> feat(): make LocalResourceResolver public

- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/KeySources.java
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/digest/DigestSources.java
- daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/CipherSourcesTest.java
- daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/KeySourcesTest.java
Deriving a key from a password and salt using PBKDF2 will likely be required by various Talend libraries.
> Adding a new KeySource implementation for pbkdf2

- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AuditConfiguration.java
- daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AuditConfigurationTest.java
- daikon-audit/audit-common/src/test/resources/test.audit.properties
- daikon-audit/audit-log4j1/src/main/java/org/talend/logging/audit/log4j1/Log4j1Configurer.java
- daikon-audit/audit-logback/src/main/java/org/talend/logging/audit/logback/LogbackConfigurer.java
Following TDKN-245, some users may want to configure host information for Audit properties instead of direct from the logger implementation configuration.
This PR adds a "host" configuration (similar to "location" configuration) that allows to configure host information display.
With this change, daikon-audit allows both host information display configuration from programmatic access *and* file based configuration.
https://jira.talendforge.org/browse/TDKN-245
> feat(TDKN-245): Allow host info configuration from code

- daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/Log4j2JSONLayout.java
- daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/Log4j2JSONLayoutTest.java
- daikon-logging/logging-event-layout/src/test/resources/log4j2.xml
The `KeyValuePair` defined in the log4j2.xml are defined as static in the layout. 
This leads anyone having defined two appenders with a variable named in the same way to get always the value defined in the last initialized appender.
By removing the static modifier for the `additional attributes`, each logger now has its own pairs and each appender can use the same key rather than having to use different ones.
> fix(logs): Make the KeyValuePair per logger

- daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/Log4j2JSONLayout.java
- pom.xml
As part of the release of the log4j2 version 2.8.2 the signature of the newInstance method of the
[ThrowablePatternConverter](https://github.com/apache/logging-log4j2/commit/0146bbae4a94aee9e92e1ba843f0125075debfdc#diff-4e590f92b3ef7722ecadcef79392a7bcR54) was changed leading to an incompatibility between daikon and application using a
more recent version than the 2.7.
This commit bumps the version of log4j2 to 2.11.2.
[https://jira.talendforge.org/browse/TDKN-247](https://jira.talendforge.org/browse/TDKN-247)
**Breaking change**
Incompatibility with versions prior to version 2.8.2
> chore(TDKN-247/logs: Bump log4j2 version to 2.11.2

- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/http/HttpEventSender.java
jaxb is no more available in the JVM so we can't rely on it - and don't want to add that dep.
Use standard Base64 API
> chore(audit/dep) don't use jaxb to create a base64 since dependency is no more there OOTB

- daikon-crypto/daikon-signature-verifier/src/main/java/org/talend/daikon/signature/verify/ZipVerifier.java
Just a trivial merge to re-use a File object that we created with JarFile instead of passing in the raw file name.
> Re-use File object

- daikon/pom.xml
- pom.xml
The Avro dependency is pulling in an old Commons Compress version which has CVEs associated with it, e.g.:
http://zookeeper.apache.org/security.html#CVE-2019-0201
We need to exclude that dependency and add a dependency on Commons Compress 1.18.0 until we update to Avro 1.9.0.
> TDKN-251 - Exclude Commons Compress from Avro dependency

- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/CipherSources.java
- daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/CipherSourcesTest.java
In the CipherSources class, we can get an AES-GCM cipher source with an arbitrary IV length, but the authentication tag length is hard coded at 8 times the IV length. In fact there should be no real relationship, and we should make the authentication tag length configurable. The default should also change to use a 96 bit IV and 128 bit authentication tag as per the NIST recommendations.
> TDKN-253 - Make authentication tag length configuration

- daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java
Currently TokenSecurityConfiguration fail if no PathMappedEndpoints exist. We need to load this configuration class only when PathMappedEndpoints are defined
Add a ConditionalOnBean condition on the configuration class
> feat(): add ConditionalOnBean condition on TokenSecurityConfiguration

- daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java
TokenSecurityConfiguration match too much request (any request) and override other spring security custom configuration 
Register TokenSecurityConfiguration only for protected path request and do not register it if not protected path is set
> fix(TDP-7278): Do not add matcher on protected path if no one is defined

- daikon-crypto/crypto-utils/pom.xml
- pom.xml
`crypto-utils` JAR cannot be included as is by end users (especially Studio).
This PR creates an additional `bundle` artifact for crypto-utils to ease integration with OSGI world.
Loosely related to https://jira.talendforge.org/browse/TDKN-256
> chore(crypto-utils) Adds a OSGI bundle for crypto-utils module.

- pom.xml
Currently Daikon has a dependency on an old version of Commons Codec - we should update it to a newer version (I found some dodgy code that uses Random to generate cryptoraphic salts that is fixed in 1.12.0).
> TDKN-257 - Update Commons Codec

- daikon/src/main/java/org/talend/daikon/security/CryptoHelper.java
- daikon/src/main/java/org/talend/daikon/token/TokenGenerator.java
According to https://jira.talendforge.org/browse/TUP-21518, we are going to remove CryptoHelper from all of studio code, with this backport, I can pass non CryptoHelper object into TokenGenerator.generateToken() which is defined inside daikon.
Backport fix of TDKN-206 to 0.31 branch
https://jira.talendforge.org/browse/TDKN-206
> backport(TDKN-206) Update TokenGenerator.generateToken interface

- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/KeySources.java
Trivial fix to avoid creating a File object twice
> Trivial fix to avoid creating a File object twice

- daikon-crypto/crypto-utils/pom.xml
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/Encryption.java
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/KeySources.java
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/PropertiesEncryption.java
Different version of slf4j are introduced in studio jobs.
Studio has thousands of components, each component has its dependencies, some component depends on slf4j, some component does not depend on it.
Studio generates jobs(code/pom/classpath/binary etc) according to the components used, so if daikon changed scope to provided, then some jobs generated may not have slf4j in classpath, this will result in failure of running job.
So it seems removing slf4j from daikon is the best option for now.
Remove direct dependency slf4j from daikon
https://jira.talendforge.org/browse/TUP-23482
**[ ] …
> backport(TUP-23482) Remove direct dependency slf4j from daikon

- daikon-crypto/crypto-utils/pom.xml
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/Encryption.java
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/KeySources.java
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/PropertiesEncryption.java
Different version of slf4j are introduced in studio jobs.
Studio has thousands of components, each component has its dependencies, some component depends on slf4j, some component does not depend on it.
Studio generates jobs(code/pom/classpath/binary etc) according to the components used, so if daikon changed scope to provided, then some jobs generated may not have slf4j in classpath, this will result in failure of running job.
So it seems removing slf4j from daikon is the best option for now.
Remove direct dependency slf4j from crypto-utils 
https://jira.talendforge.org/browse/TUP-23482 …
> fix(TUP-23482) Remove direct dependency of slf4j

- pom.xml
We should update Commons Compress due to CVE-2019-12402
> TDKN-259 - Update Commons Compress

- daikon/src/main/java/org/talend/daikon/properties/presentation/Widget.java
- daikon/src/test/java/org/talend/daikon/properties/presentation/WidgetTest.java
* fix(TDI-42756):table widget miss hidden flag.
* fix(TDI-42756):replace reflection with PropertiesVisitor
* use recursion to set flag for nested property.
https://jira.talendforge.org/browse/TDI-42756
> Backport(TDI-42756): Table hidden flag missing

- daikon-tql/daikon-tql-client/package.json
- daikon-tql/package.json
the mono repo has been published to npm
http://npmjs.com/package/daikon-tql
the client package has dependencies never imported
remove unused dependencies
deprecate `daikon-tql` on  npm
make mono repo package a `private`
> chore(tql): make mono repo private and remove unused deps

- pom.xml
We need to update Jackson to 2.10.0 to pick up fixes for some CVEs.
> TDKN-262 - Update Jackson to 2.10.0

- daikon/src/main/java/org/talend/daikon/properties/PropertiesImpl.java
StringProperty depends on CryptoHelper to do data encryption/decryption. There is no way to switch encryption algorithms.
1) Change propsAlreadyInitialized of PropertiesImpl from private to protected so that it can overridden by subclass
2) Override two methods- postDeserialize and handleAllPropertyEncryption of PropertiesImpl in subclass, so that components of studio can decrypt old persist properties with DES algorithm and encrypt/decrypt new properties with AES algorithm
https://jira.talendforge.org/browse/TUP-21518
> feat(TUP-21518) Remove CryptoHelper31

- daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenAuthentication.java
- daikon-spring/daikon-spring-security/src/test/java/org/talend/daikon/security/token/TokenAuthenticationTest.java
One can not configure the spring-boot-actuator `ShowDetails.WHEN_AUTHORIZED` with the `TokenAuthentication` because their implementation uses internally the current `Principal` returned by the `Authentication` and the default rule is that it must be non null.
Basic implementation of the `getPrincipal` for the `TokenAuthentication` class
https://jira.talendforge.org/browse/TPSVC-11976
> fix(TPSVC-11976) don't return null as the principal

- daikon-logging/logging-request-interceptor/src/main/java/org/talend/daikon/logging/TraceRequestUtil.java
The return statement is not used, meaning that the call to replaceAll is useless.
> Fix useless call in TraceRequestUtil

- daikon-spring/daikon-content-service/s3-content-service/pom.xml
Spring Cloud AWS dependency brings an auto configuration that is overkill for a simple usage of S3 content service.
* Add dependency on "aws-java-sdk-s3" and "spring-cloud-aws-core" from Spring Cloud BOM.
* Remove dependency on "spring-cloud-aws-starter".
https://jira.talendforge.org/browse/TDKN-267
> chore(TDKN-267): Remove dependency on AWS cloud starter

- daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/access/RequiresAuthority.java
- daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/access/RequiresAuthorityActiveIfDefaults.java
- daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/access/RequiresAuthorityAspect.java
- daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/access/RequiresAuthorityConditionDefaults.java
- daikon-spring/daikon-spring-security/src/test/java/org/talend/daikon/security/access/RequiresAuthorityAspectTest.java
- daikon-spring/daikon-spring-security/src/test/java/org/talend/daikon/security/access/RequiresTestComponent.java
`@RequiresAuthority` annotation cannot be conditional.
Add an `activeIf` attribute to be able to use annotation if the condition is truthy.
https://jira.talendforge.org/browse/TDP-5002
> feat(TDP-5002): conditional requires authority

- daikon-spring/daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/AmazonS3TestWrapper.java
TPSVC use AmazonS3TestWrapper in their UT. In order to be able to migrate config-client to SB2 we need to put it on public
Add public on the AmazonS3TestWrapper constructor
> chore(TPSVC-12467): make AmazonS3TestWrapper constructor public

- daikon/src/main/java/org/talend/daikon/security/SSLContextProvider.java
In SSLContextProvider in Daikon, we have:
KeyManagerFactory kmf = KeyManagerFactory.getInstance("SunX509");
TrustManagerFactory tmf = TrustManagerFactory.getInstance("SunX509");
Please instead use KeyManagerFactory.getDefaultAlgorithm() + TrustManagerFactory.getDefaultAlgorithm(). Both will default to PKIX - note that SunX509 is not recommended (https://bugs.openjdk.java.net/browse/JDK-8169745)
> TDKN-215 - Change "SunX509" in SSLContextProvider

- daikon-crypto/daikon-signature-verifier/pom.xml
- daikon-documentation/pom.xml
- daikon-i18n/pom.xml
- daikon-scala/dynamic-log/dynamic-log-web-play/pom.xml
- pom.xml
We should update Pax URL to the latest fix to pick up a fix for a CVE:
pax-url-aether-2.4.7.jar/META-INF/maven/org.codehaus.plexus/plexus-utils/pom.xml (pkg:maven/org.codehaus.plexus/plexus-utils@3.0.17, cpe:2.3:a:plexus-utils_project:plexus-utils:3.0.17:::::::*) : Directory traversal in org.codehaus.plexus.util.Expand, Possible XML Injection
As part of the PR I also fixed a few inconsistencies with the compiler plugin I noticed.
> TDKN-268 - Update Pax URL

- daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/config/Aspects.java
Bug in TDP-8039
Change package name in annotation 
https://jira.talendforge.org/browse/TDP-8039
> fix(TDP-8039): Move LogTimed annotation to Daikon

- daikon-spring/daikon-spring-examples/daikon-spring-example-security/pom.xml
- daikon-spring/daikon-spring-examples/pom.xml
- daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java
- pom.xml
Allow to access to the `info` endpoint without sending credentials 
Treat the `info` endpoint the same way the code does for the `health` one. 
From the example spring-boot application (with the security profile used)
```bash
http :8080/actuator/info                                                    
HTTP/1.1 200 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
Date: Sat, 08 Feb 2020 15:11:05 GMT
Expires: 0
Pragma: no-cache
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
{
"build": {
"artifact": "daikon-spring-example-security", …
```
> feat(security) allow anonymous access to the version endpoint

- daikon-crypto/crypto-utils/pom.xml
- pom.xml
This PR fixes a CVE in Beanutils 1.9.3 by updating to 1.9.4. In addition, it removes a duplicate Jackson version which meant we were really including Jackson 2.9.5 instead of 2.10.1.
> Updating Beanutils to fix a CVE and removing duplicate Jackson version

- daikon-audit/audit-common/pom.xml
- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/AuditLoggerFactory.java
- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AbstractAuditLoggerBase.java
- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AbstractBackend.java
- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AuditConfiguration.java
- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/Backends.java
- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/SimpleAuditLoggerBase.java
- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/Utils.java
- daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AbstractAuditLoggerBaseTest.java
- daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AuditConfigurationTest.java
- daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/SimpleAuditLoggerBaseTest.java
- daikon-audit/audit-common/src/test/resources/test.audit.properties
- daikon-audit/audit-kafka/pom.xml
- daikon-audit/audit-kafka/src/main/java/org/talend/logging/audit/kafka/KafkaBackend.java
- daikon-audit/audit-kafka/src/test/java/org/slf4j/impl/StaticMDCBinder.java
- daikon-audit/audit-kafka/src/test/java/org/talend/logging/audit/kafka/KafkaBackendTest.java
- daikon-audit/audit-kafka/src/test/resources/audit.full.properties
- daikon-audit/audit-kafka/src/test/resources/audit.minimal.properties
- daikon-audit/pom.xml
Audit logs must be sent for Talend applications deployed on cloud. These audit logs are sent to the kafka customer logs cluster.
Reuse daikon-audit to add a Kafka backend, capable to handle audit logs and send them to a kafka broker. The goal is to capitalize on the work which has been done for audit logs on premise, without breaking the current implementation (no breaking change for the applications which already use daikon-audit)
More precisely: 2 main classes are added:
- KafkaBackend (inside the new module audit-kafka) to have the ability to send audit logs to a kafka broker. This backend is simple, without retry logic, only sends synchronously audit logs with a parametrized …
> feat(TPSVC-13659): kafka backend for audit logs

- daikon-service/pom.xml
spring-boot-starter-parent brings beanutils version 1.9.3. This version raise CVE issue.
Override beanutils version from spring-boot-starter-parent. It will fix CVE in components project and in daikon project.
https://jira.talendforge.org/browse/TDI-43723
> fix(TDI-43723): override beanutils version from spring-boot-starter

- daikon-content-service/content-service-journal-mongo/pom.xml
- daikon-logging/logging-http-headers/pom.xml
- daikon-logging/logging-kafka-interceptor/pom.xml
- daikon-messages/messages-demo/demo-listener/pom.xml
- daikon-messages/messages-demo/demo-producer/pom.xml
- daikon-messages/messages-demo/pom.xml
- daikon-messages/messages-model-spring-support/pom.xml
- daikon-messages/pom.xml
- daikon-multitenant/pom.xml
- daikon-service/pom.xml
- poc/daikon-cqrs/pom.xml
- pom.xml
We should update to Spring Boot 1.5.22 to pick up a bunch of CVE fixes (for example in Jetty). In addition, lots of the modules define their own version of Spring Boot 1.5.x, instead of picking up the root version.
https://jira.talendforge.org/browse/TDKN-276
> TDKN-276 - Update to Spring Boot 1.5.22

- daikon-spring/daikon-spring-audit-logs/README.adoc
- daikon-spring/daikon-spring-audit-logs/pom.xml
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/api/AuditContextFilter.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/api/AuditUserProvider.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/api/GenerateAuditLog.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/api/NoOpAuditContextFilter.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/api/NoOpAuditUserProvider.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditKafkaProperties.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditLogConfig.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/model/AuditLogFieldEnum.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogContextBuilder.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogGenerationFilter.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogGenerationFilterImpl.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogGenerationFilterInterface.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogger.java
- daikon-spring/daikon-spring-audit-logs/src/main/resources/META-INF/spring.factories
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/config/AuditLogConfig.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/service/AuditLogContextBuilderTest.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/service/AuditLogGenerationFilterConfiguration.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/service/AuditLogGenerationFilterImplTest.java
- daikon-spring/daikon-spring-audit-logs/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- daikon-spring/pom.xml
Most of the Talend applications generating audit logs are built using Spring. Audit log context enhancement using Spring leverage must be centralized.
As part of #596, `daikon-spring-audit-logs` has been initialized in Daikon `v2`.
The module must be ported on Daikon `v3`.
**What is the chosen solution to this problem?** 
As mentioned in #596, last step of [TPSVC-13814](https://jira.talendforge.org/browse/TPSVC-13814) is to port `daikon-spring-audit-logs` from Daikon `v2` to Daikon `v3`.
> TPSVC-13814: daikon-spring-audit-logs port from v2 to v3

- pom.xml
This task is to update BouncyCastle to 1.65. In some of the projects, we needed to ship a beta version of 1.65 due to a bug with Java 11 and TLS.
> TDKN-283 - Update BouncyCastle to 1.65

- daikon-spring/daikon-spring-audit-logs/README.adoc
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditKafkaProperties.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/model/AuditLogFieldEnum.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/service/AuditLogContextBuilderTest.java
Using cameCase for JSOn structure is the Talend recommendation.
Audit logs keys format must be updated to fit this recommendation.
Update audit logs field enum, tests and readme accordingly.
This change will be backported on v2.0 (see #601). 
https://jira.talendforge.org/browse/TPSVC-14118
> TPSVC-14118: Move audit logs JSON structure from snake case to camel case

- pom.xml
This task is to update Log4j 2 to 2.13.2 due to the following CVE:
[CVE-2020-9488] Improper validation of certificate with host mismatch in Apache Log4j SMTP appender
https://seclists.org/oss-sec/2020/q2/72
> TDKN-284 - Update Log4j 2 to 2.13.2

- pom.xml
This task is to update BouncyCastle to 1.65. In some of the projects, we needed to ship a beta version of 1.65 due to a bug with Java 11 and TLS.
> TDKN-283 - Update BouncyCastle to 1.65 (#595)

- pom.xml
This task is to update Log4j 2 to 2.13.2 due to the following CVE:
[CVE-2020-9488] Improper validation of certificate with host mismatch in Apache Log4j SMTP appender
https://seclists.org/oss-sec/2020/q2/72
> TDKN-284 - Update Log4j 2 to 2.13.2 (#602)

- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditLogAutoConfiguration.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogGeneratorInterceptor.java
In order to read the HTTP response body from the interceptor in case of negative event, the [HttpServletResponse](https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletResponse.html) is wrapped into a [ContentCachingResponseWrapper](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/ContentCachingResponseWrapper.html).
Once the content read from `ContentCachingResponseWrapper`, the method `copyBodyToResponse()` must be called (as explained [here](https://stackoverflow.com/a/39945940/2220149 )). If this method is not called, the content remains empty and can't be read by the next filter.
In some cases, it seems that the HTTP response is empty for the next filter.
**What is …
> TPSVC-14037: Negative audit logs - fix empty response

- pom.xml
This task is to update SLF4J to 1.7.26 to pick up a CVE fix (CVE-2018-8088).
> fix(TDKN-285) Update SLF4J to 1.7.26 (#607)

- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/api/AuditLogScope.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/api/GenerateAuditLog.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogGeneratorAspect.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogGeneratorInterceptor.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/api/AuditLogTest.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/api/AuditLogTestApp.java
In some cases, complex audit logs are generated manually. In those case, the `@GenerateAuditLog` annotation is not used. As a consequence, negative events are not handled. 
A way to handle negative audit logs even in case of manually generated audit logs must be implemented.
Add a `scope` argument to `@GenerateAuditLog` annotation indicating if audit logs must be generated for :
- **ALL** cases
- **SUCCESS** cases only
- **ERROR** cases only
https://jira.talendforge.org/browse/TPSVC-14487
> TPSVC-14487: Negative events not capture when manually generating audit logs

- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/api/AuditLogScope.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/api/GenerateAuditLog.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogGeneratorAspect.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogGeneratorInterceptor.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/api/AuditLogTest.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/api/AuditLogTestApp.java
In some cases, complex audit logs are generated manually. In those case, the `@GenerateAuditLog` annotation is not used. As a consequence, negative events are not handled. 
A way to handle negative audit logs even in case of manually generated audit logs must be implemented.
Backport of #612
Add a `scope` argument to `@GenerateAuditLog` annotation indicating if audit logs must be generated for :
- **ALL** cases
- **SUCCESS** cases only
- **ERROR** cases only
https://jira.talendforge.org/browse/TPSVC-14487
> TPSVC-14487: Negative events not capture when manually generating audit logs (backport)

- daikon-spring/daikon-spring-audit-logs/pom.xml
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditLogAutoConfiguration.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogGeneratorInterceptor.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/api/AuditLogTest.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/api/AuditLogTestApp.java
In case of negative events, request body is retrieved by the interceptor as `String` value.
In some cases, a filter is used in order to hide some fields of request body. Most of the time, the filters expect an `Object` and not a `String`.
In order to let the filters filtering requests even in case of negative events, `String` request must be parsed before being added to the context.
- Retrieve `@RequestBody` annotation and corresponding parameter type if possible
- Try to parse `String` request into the retrieved type
- If parsing fails, use the `String` format
https://jira.talendforge.org/browse/TPSVC-14487
**Please check if the Pull Request fulfills …
> TPSVC-14487: Parse request in case of negative audit logs

- daikon-spring/daikon-spring-zipkin/src/main/java/org/talend/daikon/zipkin/ZipkinKafkaSenderConfiguration.java
Override the auto-configuration of Zipkin
Following the [Spring documentation](https://cloud.spring.io/spring-cloud-sleuth/2.1.x/single/spring-cloud-sleuth.html#_overriding_the_auto_configuration_of_zipkin), update the kafkaSender bean name and define a Reporter bean.
More info: 
https://github.com/spring-cloud/spring-cloud-sleuth/blob/2.1.x/spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/sender/ZipkinKafkaSenderConfiguration.java#L39
https://jira.talendforge.org/browse/TDP-8780 
**Fix wanted in the Daikon 2.0.x version**
**[ ] This Pull Request introduces …
> feat(TDP-8780): Update ZipkinKafkaSenderConfiguration bean definition

- daikon-audit/audit-log4j2/src/main/java/org/talend/logging/audit/log4j2/Log4j2Configurer.java
fix log4j2 wrong setting for filepattern
correct it only
https://jira.talendforge.org/browse/TDI-44172
> fix(TDI-44172): fix the log4j2 issue

- daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ContentServiceConfiguration.java
- daikon-spring/daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/S3ContentServiceConfigurationTest.java
S3 bucket is set a sub domain instead of path when the minio authentication is set
Configure the client to use path-style access for request instead of virtual-hosted-style
> fix: set the S3 bucket as a URL path for MINIO configuration

- daikon-spring/daikon-content-service/s3-content-service/README.md
- daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ContentServiceConfiguration.java
- daikon-spring/daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/S3ContentServiceConfigurationTest.java
Path is enabled by default for Minio access yet it remains impossible:
* To disable path style access for Minio
* To enable/disable path style access for other modes.
Introduce a new property to configure behavior without impacting current default behaviors.
> feat(s3) S3 configuration improvement

- daikon-spring/daikon-spring-audit-logs/README.adoc
- daikon-spring/daikon-spring-audit-logs/pom.xml
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditLogAutoConfiguration.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditProperties.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogContextBuilder.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogIpExtractor.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogIpExtractorImpl.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSender.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSenderImpl.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/api/AuditLogTest.java
In the scope of [TPSVC-14747](https://jira.talendforge.org/browse/TPSVC-14747) is has been decided to not let services handling `x-forwarded-for` header by themselves.
For that purpose, the following property is defined for the TPSVC services :
`server.use-forward-headers: false`
As a consequence, retrieving the remote id address from the request using `request.getRemoteAddr()` is no more relevant.
The solution is to extract the public ip from the `x-forwarded-for` header.
In order to prevent forgery attempts, all public ips are retrieved.
In order to deal with WAF, a new property `audit.trusted-proxies` is added. 
Trusted public IPs are filtered based on that pattern.
**Link to …
> TPSVC-15007: Extract public remote ip(s) from x-forwarded-for header

- daikon-spring/daikon-spring-audit-logs/README.adoc
- daikon-spring/daikon-spring-audit-logs/pom.xml
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditLogAutoConfiguration.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditProperties.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogContextBuilder.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogIpExtractor.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogIpExtractorImpl.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSender.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSenderImpl.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/api/AuditLogTest.java
In the scope of [TPSVC-14747](https://jira.talendforge.org/browse/TPSVC-14747) is has been decided to not let services handling `x-forwarded-for` header by themselves.
For that purpose, the following property is defined for the TPSVC services :
`server.use-forward-headers: false`
As a consequence, retrieving the remote id address from the request using `request.getRemoteAddr()` is no more relevant.
The solution is to extract the public ip from the `x-forwarded-for` header.
In order to prevent forgery attempts, all public ips are retrieved.
In order to deal with WAF, a new property `audit.trusted-proxies` is added. 
Trusted public IPs are filtered based on that pattern.
Backport …
> TPSVC-15007: Extract public remote ip(s) from x-forwarded-for header (backport)

- daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/BeanPredicateVisitor.java
- daikon-tql/daikon-tql-bean/src/test/java/org/talend/tql/bean/BeanPredicateVisitorTest.java
When using "=" operator with BeanPredicateVisitor, comparison is performed on string equals. This cause `field = 10` and `field = 10.0` to be differently interpreted.
* Fix BeanPredicateVisitor predicate creation when using "=" with a numeric value.
* Add unit test for issue.
https://jira.talendforge.org/browse/TDKN-293
> fix(TDKN-293): Fix number comparison when using "="

- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogIpExtractorImpl.java
In some cases, `x-forwarded-for` header is missing and ip address retrieved from `HttpServletRequest.getRemoteAddr()` is an internal address (dev cluster, local, ...). In these cases the audit log is not generated and an error is thrown because ip address is missing (because filtered out).
Filter out internal/trusted ip addresses only when ip addresses come from `x-forwarded-for` header.
Otherwise, retrieve unfiltered remote addr.
https://jira.talendforge.org/browse/TPSVC-15007
> TPSVC-15007: [AUDIT LOGS] Extract IPs from x-forwarded-for header & filter WAF IPs (backport)

- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogIpExtractorImpl.java
In some cases, `x-forwarded-for` header is missing and ip address retrieved from `HttpServletRequest.getRemoteAddr()` is an internal address (dev cluster, local, ...). In these cases the audit log is not generated and an error is thrown because ip address is missing (because filtered out).
Filter out internal/trusted ip addresses only when ip addresses come from `x-forwarded-for` header.
Otherwise, retrieve unfiltered remote addr.
https://jira.talendforge.org/browse/TPSVC-15007
> TPSVC-15007: [AUDIT LOGS] Extract IPs from x-forwarded-for header & filter WAF IPs

- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogIpExtractorImpl.java
On the dev cluster, calling public ingress, we have these ips : 
- **Remote addr :** 10.223.64.69
- **x-forwarded-for header :** 10.223.38.137
In this case, during audit log generation, the ip is extracted from `x-forwarded-header`. 
The ip `10.223.38.137` is then filtered out as it is an internal ip. 
As a consequence, because ip field is mandatory for audit logs, an error is thrown and the audit log can't be generated.
Try to extract and filter the ips from `x-forwarded-for` header and use normal remote ip if result is empty.
> TPSVC-15007: Use remote addr if ip extracted from x-forwarded-for header is empty

- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogIpExtractorImpl.java
On the dev cluster, calling public ingress, we have these ips : 
- **Remote addr :** 10.223.64.69
- **x-forwarded-for header :** 10.223.38.137
In this case, during audit log generation, the ip is extracted from `x-forwarded-header`. 
The ip `10.223.38.137` is then filtered out as it is an internal ip. 
As a consequence, because ip field is mandatory for audit logs, an error is thrown and the audit log can't be generated.
Try to extract and filter the ips from `x-forwarded-for` header and use normal remote ip if result is empty.
Backport of #633
**[ ] This Pull Request introduces a breaking …
> TPSVC-15007: Use remote addr if ip extracted from x-forwarded-for header is empty (backport)

- daikon-spring/daikon-content-service/README.md
- daikon-spring/daikon-content-service/content-service-common/pom.xml
- daikon-spring/daikon-content-service/content-service-common/src/main/java/org/talend/daikon/content/AbstractResourceResolver.java
- daikon-spring/daikon-content-service/content-service-journal-mongo/src/main/java/org/talend/daikon/content/journal/MongoResourceJournalResolver.java
- daikon-spring/daikon-content-service/content-service-journal/pom.xml
- daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/JournalizedDeletableResource.java
- daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/JournalizedResourceResolver.java
- daikon-spring/daikon-content-service/s3-content-service/pom.xml
- daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ResourceResolver.java
- daikon-spring/daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/S3ContentServiceConfigurationTest.java
- daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/config/MetricsConfiguration.java
To provide better production issue insights, it would be nice to have a way to track time spent in ResourceResolver methods. 
* Leverage aspects provided by daikon-spring-metrics
* Mark resource resolver methods as time monitored (see daikon-spring-metrics).
https://jira.talendforge.org/browse/TDKN-294
> feat(TDKN-294) Add support for time monitoring for content service

- daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/FixedURLS3Resource.java
- daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ContentServiceConfiguration.java
- daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ResourceResolver.java
- daikon-spring/daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/FixedURLS3ResourceTest.java
- daikon-spring/daikon-content-service/s3-content-service/src/test/resources/application.properties
By default Spring S3 resources rely on AWS client region to build URL/URI. This works fine for a AWS environment but causes issues when using a custom endpoint (Minio case).
This PR fixes the build of URLs and URIs when using a MINIO/CUSTOM authentication mode in content service.
> fix(content-service) Fix getUrl/getUri when using custom authentication mode

- daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/JournalizedResourceResolver.java
- daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/LazyDeletableResource.java
- daikon-spring/daikon-content-service/content-service-journal/src/test/java/org/talend/daikon/content/journal/JournalizedResourceResolverTest.java
Note: This is `maintenance/2.0`version of PR #636 
When using getResources on a journalized content service, each returned result causes a save operation in the journal. Even if each save operation doesn't last long, this cause 2 issues:
* It's a useless save (it's about writing an information that has just been read).
* When returning a lot of resources, this adds an overhead.
* Prevent useless journal save calls during resource list
* Add unit tests to ensure expected behavior
> chore(journal): Performance improvement for content journal (2.0)

- daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/JournalizedResourceResolver.java
- daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/LazyDeletableResource.java
- daikon-spring/daikon-content-service/content-service-journal/src/test/java/org/talend/daikon/content/journal/JournalizedResourceResolverTest.java
When using getResources on a journalized content service, each returned result causes a save operation in the journal. Even if each save operation doesn't last long, this cause 2 issues:
* It's a useless save (it's about writing an information that has just been read).
* When returning a lot of resources, this adds an overhead. 
* Prevent useless journal save calls during resource list
* Add unit tests to ensure expected behavior
> chore(journal): Performance improvement for content journal

- daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/LocationUtils.java
- daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ResourceResolver.java
S3 Resource resolver is able to return DeletableResource instances that works fine with Minio. However when accessing results of getResources, returned results do not benefit from the fix.
* Group common code between getResource() and getResources() for S3 access
* Fix potential NPE in toS3Location.
> fix(content-service) Ensure both getResource and getResources are fixed

- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSenderImpl.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/api/AuditLogTest.java
https://jira.talendforge.org/browse/TPSVC-15266
Kibana logs show us a lot of errors alike
`org.talend.daikon.spring.audit.logs.exception.AuditLogException: UNEXPECTED_EXCEPTION:{message=audit log context is incomplete, missing information: [ACCOUNT_ID]}`
During investigation were found that in all cases it is because unauthenticated user tries to access resource
So the solution is to lower log level for this type of exceptions
> feat(TPSVC-15266): lower log level for AuditLogException

- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/digest/DigestSources.java
- daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/digest/DigestSourcesTest.java
DigestSources.sha256 is not actually digesting the salt with the password...it is just digesting them separately and appending them, which defeats the purpose of using a salt. Thankfully, we are not actually using this anywhere.
> TDKN-295 - DigestSources.sha256 not mixing salt with password

- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogContextBuilder.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/api/AuditLogTest.java
https://jira.talendforge.org/browse/TPSVC-15563 : [AZ-sandbox] Public api is not accessible through Portal
The issue is that on Azure sandbox  thre is port number in X-Forwarded-Host header which causes exception during audit log generation
Remove the port part from header before creating URI
> feat(TPSVC-15563): remove port from X-Forwarded-Host

- daikon-audit/README.adoc
- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AbstractAuditLoggerBase.java
- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AbstractBackend.java
- daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AbstractAuditLoggerBaseTest.java
- daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AbstractBackendTest.java
Audit event message processing (including variable substitution) can be a costly operation, especially in use cases when a very high throughput is expected and message is discarded.
* Add MDC field to configure whether message go to output or not.
* Update README documentation with additional information.
https://jira.talendforge.org/browse/TDKN-297
> feat(TDKN-297): Add ability to disable message output

- daikon-audit/README.adoc
- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AbstractAuditLoggerBase.java
- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AbstractBackend.java
- daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AbstractAuditLoggerBaseTest.java
- daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AbstractBackendTest.java
This PR backports the enhancement brought by [TDKN-297](https://jira.talendforge.org/browse/TDKN-297) to the 1.x maintenance branch (used in the jobs)
Cherry-pick the feature commits
[TDKN-297](https://jira.talendforge.org/browse/TDKN-297)
> feat(TDKN-297): backport disable message output

- daikon-spring/daikon-spring-audit-logs/pom.xml
This task is to update Commons Validator to 1.7 in daikon-spring-audit-logs. This fixes a high level CVE in a transitive dependency (BeanUtils 1.9.2).
> TDKN-298 - Update Commons Validator to 1.7 in daikon-spring-audit-logs

- daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/BeanPredicateVisitor.java
- daikon-tql/daikon-tql-bean/src/test/java/org/talend/tql/bean/BeanPredicateVisitorTest.java
There's an issue in value type inference (based on method return type). When path contain multiple elements, type is taken from first path element instead of last one.
* Make sure to infer type based on last part of path.
https://jira.talendforge.org/browse/TDC-4420
> fix(TDC-4420): Fix incorrect value type inference for path expressions

- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditLogAutoConfiguration.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogGeneratorAspect.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/ResponseExtractor.java
**What is the problem this Pull Request is trying to solve?** 
wrong response body and code is logged in audit logs in TMC web app
add response extractor bean to make more flexible mechanism to extract right response code
https://jira.talendforge.org/browse/TMC-22830
> bug(TMC-22830) wrong response body is logged in audit logs

- pom.xml
This task is to update Jackson 1.9.13/14-TALEND to 1.9.15-TALEND, which has fixes for many recent CVEs.
> TDKN-299 - Update Jackson 1.9.x to 1.9.15-TALEND

- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/api/GenerateAuditLog.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditLogAutoConfiguration.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/model/AuditLogFieldEnum.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogContextBuilder.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogGeneratorAspect.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogGeneratorInterceptor.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSender.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSenderImpl.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/ResponseExtractor.java
Response body is null for CREATE operation for all create operations in TMC
add location header to log, to keep track of entities that was created 
https://jira.talendforge.org/browse/TMC-23122
> TMC-23122 [Audit Log] Response body is null for CREATE operation

- daikon-crypto/daikon-signature-verifier/pom.xml
- daikon-crypto/daikon-signature-verifier/src/test/java/org/talend/daikon/signature/verify/CertificateGenerater.java
@RyanSkraba reported to me that the signature verifier tests fail on his machine. I think this is due to the fact that the tests use the internal Sun APIs. Instead I changed the tests to generate certificates using BouncyCastle instead, which means it should run on any JVM.
> Removing internal sun APIs from the CertificateGenerater

- pom.xml
Veracode is reporting a new CVE for Apache HTTP Client:
"httpclient is vulnerable to validation bypass. A malformed authority component in the request URIs that is passed to the library as `java.net.URI` object would result in the request execution for a wrong target host."
CVE-2020-13956
This issue was fixed in version 4.5.13
> TDKN-301 - Update HttpClient to 4.5.13

- daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/BeanPredicateVisitor.java
- daikon-tql/daikon-tql-bean/src/test/java/org/talend/tql/bean/BeanPredicateVisitorTest.java
- daikon-tql/daikon-tql-core/src/main/antlr4/TqlLexer.g4
- daikon-tql/daikon-tql-core/src/main/antlr4/TqlParser.g4
- daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldIsNullExpression.java
- daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/parser/TqlExpressionVisitor.java
- daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/visitor/IASTVisitor.java
- daikon-tql/daikon-tql-mongo/src/main/java/org/talend/tqlmongo/ASTVisitor.java
- daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Complex.java
A field comparison operator should be added to the grammar for allow `field is null` type of predicates.
Add a `is null` operator to TQL and derived implementations (MongoDB and object predicates).
> feat(tql) Add support for "is null" operator

- daikon-tql/daikon-tql-client/package.json
- daikon-tql/daikon-tql-client/src/converter/__tests__/query.spec.js
- daikon-tql/daikon-tql-client/src/converter/operators/operator.js
Operand are not escaped, resulting in unparseable query:
`((0001 = 'Au p'tit pain nantais'))`
should be
`((0001 = 'Au p\'tit pain nantais'))`
> fix(tql-client): Escape ' char

- daikon-spring/daikon-spring-audit-logs/pom.xml
- pom.xml
There are some medium level CVEs in Daikon due to transitive dependencies of commons-io / commons-codec that we can update.
> TDKN-305 - Update Commons IO + Commons Codec

- daikon-logging/logging-event-layout/src/main/resources/mdc_ecs_mapping.properties
Custom field `accountId` is mapped to the ECS field `cloud.account.id` used by Filebeat.
Map `accountId` to another suitable field.
> fix(TPSVC-17135): Do not use ECS cloud.account.id field

- pom.xml
[Avro 1.10.2](https://github.com/apache/avro/releases/tag/release-1.10.2) is released with bugfixes and CVE updates.  This is a minor (not patch) release with source compatibility with 1.10.1.
Bump! 
- [] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
> chore: Bump Avro to 1.10.2

- pom.xml
Updating JSON Smart to fix a CVE issue in versions before 2.4.1.
> Updating JSON Smart to 2.4.2

- daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/ecs/EcsSerializer.java
- daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/LogbackJSONAccessEventLayout.java
- daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/ecs/EcsSerializerTest.java
- daikon-logging/logging-spring-test/src/test/java/org/talend/daikon/logging/spring/AccessLogbackJsonLayoutTest.java
`LogbackJSONAccessEventLayout` does not respect ecs format for `event.duration`, `event.start|end` fields.
Fix them
> fix(web event) duration is nanoseconds, event.start|end are date

- pom.xml
Updating Commons Codec to 1.14 as per other maintenance branches, to fix a CVE.
> Updating Commons Codec to 1.14

- daikon-audit/audit-kafka/src/main/java/org/talend/logging/audit/kafka/KafkaBackend.java
- daikon-spring/daikon-spring-audit-logs/README.adoc
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditKafkaProperties.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditLogAutoConfiguration.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSenderImpl.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/api/AuditLogTest.java
Client application is blocked if audit log can't generated due to Kafka issue.
Losing logs is more acceptable than having Talend Cloud down.
As a consequence, the fact that Kafka is down shouldn't block the client application.
In that case a simple log is generated.
The Kafka send timeout can now be configured from the client application.
https://jira.talendforge.org/browse/TPSVC-15956
> feat(TPSVC-15956): [Audit-log] Mitigate audit log failure impact on login

- daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AuditConfiguration.java
- daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AuditConfigurationTest.java
- daikon-audit/audit-common/src/test/resources/test.audit.properties
- daikon-audit/audit-kafka/src/main/java/org/talend/logging/audit/kafka/KafkaBackend.java
- daikon-audit/audit-kafka/src/test/java/org/talend/logging/audit/kafka/KafkaBackendTest.java
- daikon-audit/audit-kafka/src/test/resources/audit.full.properties
- daikon-spring/daikon-content-service/s3-content-service/pom.xml
- daikon-spring/daikon-spring-audit-logs/README.adoc
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditKafkaProperties.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditLogAutoConfiguration.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSenderImpl.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/api/AuditLogTest.java
Thanks to #735 the operations generating audit logs still work if Kafka is down. 
But the client apps are still blocked during 60 seconds and this timeout can't be configured.
Use `max.block.ms` Kafka producer property to define the blocking timeout (other than default 60000 ms).
Provide a way for the client apps to configure it.
https://jira.talendforge.org/browse/TPSVC-15956
> fix(TPSVC-15956): [Audit-log] Mitigate audit log failure impact on login - Fix Kafka block timeout

- daikon-spring/daikon-spring-audit-logs/README.adoc
- daikon-spring/daikon-spring-audit-logs/pom.xml
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditLogAutoConfiguration.java
- daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSenderImpl.java
- daikon-spring/daikon-spring-audit-logs/src/test/java/org/talend/daikon/spring/audit/logs/api/AuditLogTest.java
We don't have any metric regarding the number of audit logs generated. Thus we can't implement the coverage SLO
Implement a prometheus counter for audit logs which will be incremented each time an audit logs is generated 
https://jira.talendforge.org/browse/TPSVC-13666
> feat(TPSVC-13666): [Audit logs] Implement a prometheus counter for audit logs

- daikon/src/main/java/org/talend/daikon/security/CryptoHelper.java
CryptoHelper is deprecated and we need to discourage it's use outside of Daikon. It has some Base64 helper static methods that are used by a few classes outside of daikon, I have filed JIRAs to fix these. We should make the methods private to discourage outside classes calling them.
> TDKN-309 - Make CryptoHelper base64 methods private

- pom.xml
This task is to update JSON Smart to 2.4.7, to pick up a CVE fix in 2.4.5 that is 9.1 High:
json-smart is vulnerable to denial of service (DoS). An unhandled ArrayIndexOutOfBoundsException thrown from the indexOf function of JSONParserByteArray allows a remote attacker to crash the program or leak confidential information.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-31684
Options
> TDKN-311 - Update JSON Smart to 2.4.7

- daikon-crypto/crypto-utils/README.md
- daikon-crypto/crypto-utils/pom.xml
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/digest/Argon2PasswordDigester.java
- daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/digest/BCryptPasswordDigester.java
- daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/digest/Argon2PasswordDigesterTest.java
- daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/digest/BCryptPasswordDigesterTest.java
Right now we only support PBKDF2, whereas bcrypt is widely implemented at Talend. This task is to add a PasswordDigester implementation based on argon2id + bcrypt + to document it.
> TDKN-313 - Support argon2id and bcrypt as a password digester

- pom.xml
Veracode reports mutiple medium level CVEs against the Kafka clients version we use in Daikon (0.10.0.0), e.g.:
https://sca.analysiscenter.veracode.com/workspaces/gZZUxkE/issues/vulnerabilities/57736058
"kafka-clients is vulnerable to user impersonation attacks. The vulnerabilities exists due to the lack of authentication checks in the `SASL/PLAIN` and `SASL/SCRAM` authentication methods using the built-in `PLAIN` or `SCRAM` server implementation in kafka-clients."
CVE-2017-12610
We should update to 2.5.1 to align with the audit logs service.
> TDKN-314 - Update Kafka version to 2.5.1

- Jenkinsfile-srcclr
Taken from https://github.com/Talend/tmdm-server-ee/blob/master/org.talend.mdm.nsis/Jenkinsfile-srcclr
Daikon needs to be regularly scanned for dependencies via Jenkins + Veracode
Integrate a Jenkins job that will regularly scan the dependencies
- [NA] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [NA] Docs have been added / updated (for bug fixes / features)
- [NA] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request
> chore(): Create SCA scan Jenkins job

- daikon-spring/daikon-spring-examples/daikon-spring-example-metrics/pom.xml
- daikon-spring/daikon-spring-examples/daikon-spring-example-metrics/src/main/java/org/talend/demo/Worker.java
- daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/java/org/talend/demo/actuator/ActuatorApplication.java
- daikon-spring/daikon-spring-examples/pom.xml
Spring samples use a different POM hierarchy which makes SB upgrades very error prone.
* Change parent hierarchy for Spring examples (to ease next releases).
> chore(versions) Inherits from daikon SB versions

- Jenkinsfile-srcclr
The previous Jenkinsfile-srcclr was broken because git clone wouldn't launch, it's unnecessary
Remove it !
> Fix(): Remove useless git clone stage from Jenkinsfile-srcclr

- Jenkinsfile-srcclr
The current SCA job isn't working, resulting in an error 
```
process apparently never started in /home/jenkins/agent/workspace/daikon-security/daikon-srcclr@tmp/durable-d66df695
(running Jenkins temporarily with -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true might make the problem clearer)
```
Switching to a TSBI builder image should fix the problem
> Fix(): Switch srcclr jenkins image to jdk8-svc-springboot-builder

- daikon-spring/daikon-spring-reactive/daikon-spring-reactive-auth/src/main/java/org/talend/daikon/spring/reactive/sat/config/ReactiveAuthenticationManagerFactory.java
- daikon-spring/daikon-spring-reactive/daikon-spring-reactive-auth/src/main/java/org/talend/daikon/spring/reactive/sat/introspection/AuthUserDetailsConverterIntrospector.java
Entitlements are not correctly mapped in Opaque workflow
Map the user details and entitlements correctly in opaque workflow
> fix(TPRUN-3858) Map the entitlements correctly in Opaque workflow
